import bundle from "../../public/projects/hangar-cold-open.json";
import type { FilmProject } from "./types";
import { validatePatch } from "./validation";

// Generated by scripts/hangar/build-project.mjs from docs/hangar/cold-open.fountain; verify:hangar checks it.
const project = bundle as FilmProject;
validatePatch(project as unknown as Record<string, unknown>);

// Database timestamps are assigned on insertion, not copied from the portable JSON's strings.
export const hangarProject: Omit<FilmProject, "createdAt" | "updatedAt" | "shareId"> = {
  id: project.id,
  title: project.title,
  description: project.description,
  genre: project.genre,
  format: project.format,
  status: project.status,
  coverImage: project.coverImage,
  acts: project.acts,
  scenes: project.scenes,
  frames: project.frames,
  script: project.script,
  notes: project.notes,
  characters: project.characters,
  brainstorm: project.brainstorm,
  moodboards: project.moodboards,
};
