import bundle from "../../public/projects/hangar-cold-open.json";
import { createHash } from "node:crypto";
import type { FilmProject, ProjectPatch } from "./types";
import hangarSync from "./hangar-sync.json";
import { validatePatch } from "./validation";
import { bundledAudioUpdates } from "./bundle-refresh";

// Generated by scripts/hangar/build-project.mjs from docs/hangar/cold-open.fountain; verify:hangar checks it.
const project = bundle as FilmProject;
validatePatch(project as unknown as Record<string, unknown>);

// Database timestamps are assigned on insertion, not copied from the portable JSON's strings.
export const hangarProject: Omit<FilmProject, "createdAt" | "updatedAt" | "shareId"> = {
  id: project.id,
  title: project.title,
  description: project.description,
  genre: project.genre,
  format: project.format,
  status: project.status,
  coverImage: project.coverImage,
  acts: project.acts,
  scenes: project.scenes,
  frames: project.frames,
  script: project.script,
  notes: project.notes,
  characters: project.characters,
  brainstorm: project.brainstorm,
  moodboards: project.moodboards,
};

/**
 * Bring a saved copy of the cold open up to the current bundle without touching the owner's edits: a field
 * whose saved value is still one the bundle shipped before (recorded as hashes by
 * scripts/hangar/record-versions.mjs) is replaced by the current value; any other value is the owner's own and stays.
 * Frames, scenes, cast and notes the owner added or deleted are neither added nor restored.
 */
type Shipped = Record<string, Record<string, string[]>>;
const shipped = hangarSync as unknown as { project: Record<string, string[]> } & Record<string, Shipped>;
const hashOf = (value: unknown) => createHash("sha256").update(JSON.stringify(value ?? null)).digest("hex");

function refreshItems<T extends { id: string }>(saved: T[], current: T[], known: Shipped | undefined): T[] {
  const arrived = new Map(current.map(item => [item.id, item]));
  let changed = false;
  const next = saved.map(item => {
    const target = arrived.get(item.id);
    const prior = known?.[item.id];
    if (!target || !prior) return item;
    let out = item;
    for (const key of Object.keys(prior)) {
      const was = (item as Record<string, unknown>)[key];
      const now = (target as Record<string, unknown>)[key];
      if (JSON.stringify(was) === JSON.stringify(now)) continue;
      if (prior[key].includes(hashOf(was))) out = { ...out, [key]: now };
    }
    if (out !== item) changed = true;
    return out;
  });
  return changed ? next : saved;
}

export function hangarUpdates(existing: FilmProject): ProjectPatch | null {
  const patch: Record<string, unknown> = {};
  const frames = refreshItems(existing.frames, project.frames, shipped.frames);
  if (frames !== existing.frames) patch.frames = frames;
  const scenes = refreshItems(existing.scenes, project.scenes, shipped.scenes);
  if (scenes !== existing.scenes) patch.scenes = scenes;
  const characters = refreshItems(existing.characters, project.characters, shipped.characters);
  if (characters !== existing.characters) patch.characters = characters;
  const notes = refreshItems(existing.notes, project.notes, shipped.notes);
  if (notes !== existing.notes) patch.notes = notes;
  for (const key of ["title", "description", "coverImage"] as const) {
    if (existing[key] !== project[key] && shipped.project[key]?.includes(hashOf(existing[key]))) patch[key] = project[key];
  }
  // 8 October 2026: the cold open's recorded voices and sound effects (frames that have no audio take the bundle's, once)
  const audio = bundledAudioUpdates({ ...existing, frames: (patch.frames as FilmProject["frames"] | undefined) ?? existing.frames }, project);
  if (audio?.frames) patch.frames = audio.frames;
  return Object.keys(patch).length ? (patch as ProjectPatch) : null;
}
