import bundle from "../../public/projects/hangar-cold-open.json";
import type { FilmProject, ProjectPatch } from "./types";
import { validatePatch } from "./validation";

// Generated by scripts/hangar/build-project.mjs from docs/hangar/cold-open.fountain; verify:hangar checks it.
const project = bundle as FilmProject;
validatePatch(project as unknown as Record<string, unknown>);

// Database timestamps are assigned on insertion, not copied from the portable JSON's strings.
export const hangarProject: Omit<FilmProject, "createdAt" | "updatedAt" | "shareId"> = {
  id: project.id,
  title: project.title,
  description: project.description,
  genre: project.genre,
  format: project.format,
  status: project.status,
  coverImage: project.coverImage,
  acts: project.acts,
  scenes: project.scenes,
  frames: project.frames,
  script: project.script,
  notes: project.notes,
  characters: project.characters,
  brainstorm: project.brainstorm,
  moodboards: project.moodboards,
};

const IMAGE_SLOT_NOTE = "No picture yet: this card holds the shot's slot.";
const PRE_IMAGE_DESCRIPTION = "The cold open of an animated 1975 feature: a pilot who sounds amazed, a crate marked INERT, a truck, a near-miss, and a crate that is empty. About six minutes, 8 scenes, 39 shots, almost no dialogue, in the house style Painted Americana '75. No pictures yet.";

/** Fill only explicitly unillustrated slots in an older saved copy of this bundled workspace. */
export function deliveredHangarImageUpdates(existing: FilmProject): ProjectPatch | null {
  if (existing.id !== project.id) return null;
  const arrivals = new Map(project.frames.map(frame => [frame.id, frame]));
  let framesChanged = false;
  const frames = existing.frames.map(frame => {
    const delivered = arrivals.get(frame.id);
    if (frame.image || !delivered?.image || !frame.notes.includes(IMAGE_SLOT_NOTE)) return frame;
    framesChanged = true;
    const guidance = delivered.image.endsWith("shot-01-03-black.png")
      ? "This full-black image is intentional; sound and pacing carry the beat."
      : "An illustrated study is attached; keep it Needs review until composition and continuity are approved.";
    return { ...frame, image: delivered.image, notes: frame.notes.replace(IMAGE_SLOT_NOTE, guidance) };
  });

  const patch: ProjectPatch = {};
  if (framesChanged) patch.frames = frames;
  if (!existing.coverImage && project.coverImage) patch.coverImage = project.coverImage;
  if (existing.description === PRE_IMAGE_DESCRIPTION) patch.description = project.description;
  return Object.keys(patch).length ? patch : null;
}
