// Hand-authored production metadata. Dialogue and episode summaries are read from docs/rapture.
// Run npm run build:rapture to rebuild the portable project; --check detects source drift.
export const projectId = "74a9cb34-9e80-4a04-a614-000000000014";
export const sceneId = "rapture-ep4-number-fourteen";
export const coldOpenSceneId = "rapture-ep3-interview";
export const lockupSceneId = "rapture-ep2-alan";
export const createdAt = "2026-09-20T00:00:00.000Z";
export const characterId = name => `rapture-${name}`;
export const grammar = "Handheld, tight, dark. Red practical sources only. Never a wide establishing shot; never show a whole room. Dry, deadpan British black comedy, not noir, horror performance or tragedy. No pathos, no grief, no score, no reaction inserts.";
export const lockupGrammar = "Locked off, wide, deep focus, daylight, symmetrical. The camera never follows Nina. Long lenses for the road. Only the vision is handheld. Dry and procedural; Nina is unimpressed throughout, never amazed or afraid.";
export const redLight = "Red practical sources only: the letterbox, red dashboard indicators and the kettle's red indicator. Deep darkness outside those small pools. No white, blue, teal, sodium or daylight fill; red is a physical source, never an overall colour grade. Jodie's collar headlamp stays off.";
export const coldOpenGrammar = "Fixed high-corner surveillance cameras, 4:3, slight fisheye, faint burnt-in timecode. Cut between fixed angles only. The camera never moves and never gets close. The timecode runs on across the cuts so the audience can see how long this has been going. Dry, deadpan British black comedy; no score, no stings, no reaction inserts.";
export const ep3ColdOpenSceneId = "rapture-ep3-cold-open";
export const patColdOpenSceneId = "rapture-ep4-pat-cold-open";
export const scoutHutSceneId = "rapture-ep4-scout-hut";
export const patColdOpenGrammar = "Fixed high-corner surveillance cameras, 4:3, slight fisheye, faint burnt-in timecode. Cut between fixed angles only. The camera never moves and never gets close. Dusk at the first timecode, dark by the last. The blank is already under the floor before anyone knocks, and the apology arrives from behind a locked door; she is waiting for nothing and the burglars pick her house by chance. Dry, deadpan British black comedy; no score, no stings.";
export const scoutHutGrammar = "Handheld, tight, close, red practical sources only: a camping lantern and the fire door light. Never a clean wide. Dry, deadpan British black comedy, never grief or a horror performance. No score, no reaction inserts; nobody asks where anything came from.";
export const angelGrammar = "The opposite of Hell's surveillance: immaculate. Locked off, perfectly composed, centred, slightly too symmetrical. Wide lenses, everything in focus, beautiful light. It looks like an advert, and that is the joke: the angels have made themselves look tremendous and they are of no use whatsoever. No score, no stings; nothing is remarked upon.";

// First sentences carry the visual identity into the prompt studio. No invented names for unnamed roles.
const cast = [
  ["nina", "Sister Nina Doyle", "Protagonist / St Jude's", "45", "Runs St Jude's, a residential house for people the system gave up on. Self-sufficient, can re-plumb a building, lies fluently to authority; gentle with the genuinely broken, brutal with anyone coasting. Daughter of the absconding rockstar, whom she never knew. Half-angel and ineligible for sorting: nepotism, not tragedy. Faith is functional; God is her employer and she has views about management. Treats divine instruction as an unreliable supplier. Finds being called a saint ridiculous.", ["Practical", "Stubborn", "Self-sufficient"], "sage", "nina"],
  ["kath", "PC Kath Bridges", "Police / moral justice", "30s", "White British police officer in her thirties. Sincerely believes she was left behind to teach moral justice; cannot remember who said so. Maintains paperwork and cites vanished superiors. Notices the wrong details with total commitment. Mild grievance, never fear or amazement. Thinks Ray is the one who gets carried away.", ["Sincere", "Pedantic", "Aggrieved"], "sand", "kath"],
  ["ray", "PC Ray Okonjo", "Police / moral justice", "30s", "Black British police officer in his thirties. Sincerely believes he was left behind to teach moral justice; cannot remember who said so. Maintains paperwork and cites vanished superiors. Follows the wrong details nowhere. Mild grievance, never fear or amazement. Thinks Kath is the one who gets carried away.", ["Sincere", "Pedantic", "Aggrieved"], "sand", "ray"],
  ["danny", "Danny Crane", "Father / water scavenger", "40", "Forty, olive waxed jacket, canvas satchel, untidy dark hair and stubble. Scavenging for water with his daughter Jodie. Has rules: nothing off anyone still alive. Cannot let her be right because the rules are the last bit of parenting he has. Keeps a laminated rules card. Dry and occupied by logistics, never played for grief.", ["Rule-bound", "Practical", "Protective"], "sage", "danny"],
  ["jodie", "Jodie Crane", "Daughter / water scavenger", "11", "Eleven, short sandy hair, navy hoodie under an oversized olive jacket, backpack and a headlamp on her collar. The headlamp stays off in Number Fourteen. Better at crime than Danny and knows it without cruelty. Sees his rules will get them killed. Her mother was raptured and judged worthy. No pathos performance.", ["Observant", "Resourceful", "Direct"], "sand", "jodie"],
  ["martin", "Martin", "Collector / Max's father", "40s", "Failed musician in a denim jacket correct in 1994, hair long at the back on principle. Four guitars, nothing written in eleven years. Collected the rockstar's belongings at estate sales; won the terminal at auction and has it filed as period junk. Cannot reach his son. Aggrieved rather than grieving. Never learns what the machine is.", ["Possessive", "Aggrieved", "Persistent"], "clay", "martin"],
  ["max", "Max", "Flashbacks / accidental operator", "14", "Fourteen-year-old son of Martin, making a retro poster for his esports team The Raptors. Misspells it RAPTURES, balances moral-criterion bars as graphic design, sets opponents weak, asks to clear past attempts, then minimises the window. Alive, unreachable; flashbacks only. Worried he is in trouble, not wracked with guilt. The series does not laugh at him.", ["Unaware", "Competitive", "Practical"], "sand"],
  ["brenda", "Brenda", "Limbo guide", "50s", "Limbo guide in her fifties, cardigan over robes behind a folding table. Thirty years in post; customer-service warmth. Sincere and bored. Cannot tell the religions apart any more. Has no records on anyone. Talks over the cathedral's four-second reverberation.", ["Sincere", "Bored", "Courteous"], "rose", "brenda"],
  ["gordon", "Gordon", "Limbo guide", "60s", "Limbo guide in his sixties, cardigan over robes behind a folding table. Thirty years in post; customer-service warmth. Sincere and bored. Cannot tell the religions apart any more. Has no records on anyone. Talks over the cathedral's four-second reverberation.", ["Sincere", "Bored", "Courteous"], "rose", "gordon"],
  ["vassago", "Vassago", "Hell / intake manager", "50s", "Hell's intake manager in his fifties, short sleeves and a lanyard. In charge, no idea. More concerned with deflating birthday balloons than the intake collapse. Instantly accepts Tamsin's theory that Heaven stole the damned for its numbers. Investigates entirely the wrong thing.", ["Bureaucratic", "Certain", "Incompetent"], "clay", "vassago"],
  ["reek", "Reek", "Hell / intake", "30s", "Hell intake employee in his thirties. Has no opinions. Works on a grey corporate open-plan floor with a blank target board and deflating birthday balloons. Goes along with the theory that Heaven stole their queue. In the field he does the leaning-in and the demonic voice, then runs out of material and sits on the floor. Still not frightened of anything except wasting time.", ["Compliant", "Uncurious", "Bureaucratic"], "clay", "reek"],
  ["tamsin", "Tamsin", "Hell / intake investigator", "20s", "Keen Hell intake employee in her twenties carrying a folder. Proposes that Heaven stole the damned to improve its numbers. Her idea becomes the working theory immediately. Investigates the wrong thing all season. Starts enjoying being a person. In the field she interviews blanks like a survey, writing down Wales and I can only apologise with equal confidence.", ["Keen", "Sincere", "Mistaken"], "clay", "tamsin"],
  ["pat", "Pat", "Hell / undercover auditor", "70s disguise", "A demon disguised as an old lady in her seventies. Too much rouge, too many doilies, a tin containing only boiled sweets and a husband whose name changes. A cupboard of bottled water she never drinks: not bait, just a demon who doesn't drink sitting on the most valuable thing in the county. Keeps a blank chained under the floor with Malcolm; the apology comes up through the locked door. She is waiting for nothing and the burglars pick her house by chance. Keeps an arrangement going after violence but is frosty as after a parking dispute. Distinct from the woman at Number Fourteen; never substitute that woman's sheet for Pat.", ["Nosy", "Overcommitted", "Businesslike"], "rose", "pat"],
  ["malcolm", "Malcolm", "Hell / undercover auditor", "70s", "Pat's other half in the overcommitted disguise: cardigan, slippers, perfectly ordinary. Comes up out of the cellar under the stairs and turns the key behind him. Washes his hands to the elbow and hangs the tea towel back on its hook, square. Thinks the chained blank will break, cannot accept that there is nothing in him to break, and is quietly furious that it keeps apologising. The blank he and Pat keep under the floor is Graham.", ["Methodical", "Ordinary", "Quietly furious"], "clay", "malcolm"],
  ["field-officer", "Hell's third field officer", "Hell / basement interrogation", "", "A female demon with a blank chained in a cellar. Interrogating him about the missing damned, gets only the apology. Reads it as resistance by the system rather than a man doing what he is told. Has notes and thinks she is close. Surveillance grammar, never moving or close.", ["Certain", "Thorough", "Mistaken"], "clay"],
  ["angel-one", "Hariel", "Heaven / equipment recovery", "40s", "One of the Michael-adjacent recovery pair, in his forties, linen, immaculate. Sent down to recover the absconder's equipment with permissions rather than power. Fronts the pair: dead centre, perfectly composed, entirely unbothered, and has not read the report either. Smug rather than stupid and of no use whatsoever. Named in the episode-three cold open; no further backstory supplied.", ["Smug", "Authorised", "Useless"], "sand"],
  ["angel-two", "Soqed", "Heaven / equipment recovery", "30s", "One of the Michael-adjacent recovery pair, in his thirties, linen, immaculate, always slightly behind Hariel. Has not read the report and admits it. Suggests using a blank because everyone's using them; that is what they're for. Smug rather than stupid and equally useless. Named in the episode-three cold open; no further backstory supplied.", ["Smug", "Authorised", "Useless"], "sand"],
  ["alan", "Alan", "Blank / Nina's passenger", "50s", "A blank in his fifties, fleece and sensible shoes, carrying a bag for life containing another bag. Nina picks him up at a wrong lockup. The apology is not a reliable test. Not automatically the chained man from the basement; no identity link has been supplied.", ["Boring", "Compliant", "Ordinary"], "sage", "alan"],
  ["absconder", "The absconder", "1980 / angel turned rockstar", "", "An angel who steals a terminal to live inside creation in 1980. Edits appearance, charisma, confidence and musical ability to the ceiling, leaves social status at default. Conjures a guitar; writes by entering tempo and key. Gives the detached tracker to a woman he loves. Nina's father. Dies five years later and declines undo with NO. Appearance and age are not locked.", ["Wilful", "Charismatic", "Decisive"], "clay"],
  ["woman-fourteen", "The Woman — Number Fourteen", "Number Fourteen / house rules", "50s", "Woman in her fifties with grey-brown hair in an untidy bun, rumpled tan housecoat over a floral blouse, and a Tesco bag stuffed with crumpled papers. Mid-sentence when the door opens. Plays her situation as house rules and a complaint to the council. The table set for six is never played. No visible listener. This supporting character is not Pat and is not identified as a blank or demon.", ["Matter-of-fact", "Occupied", "Insistent"], "rose", "crazed-woman"],
  ["rescued-blank", "The rescued blank", "Basement / surveillance window", "", "A man chained in a cellar by Hell's third field officer. Gives the apology, doing what he is told. Rescued by Danny and Jodie; talks about laminate flooring. Hell watches through him, putting the rescuers on its map. Do not assume this is Alan. No name or age supplied.", ["Compliant", "Tedious", "Ordinary"], "sand"],
  ["graham", "Graham", "Blank / payroll", "50s", "A blank in his fifties interviewed by Hell's intake in his own front room. Beige cardigan over a shirt and tie, corduroys, slippers. Perfectly content, hands on knees, facing slightly away from anyone. Answers everything helpfully and is never frightened; the drink is hospitality. Most animated on payroll: the wages, but the deductions as well, statutory and voluntary. Says I can only apologise with no pause at all and apologises for never having made a decision. By the episode-four cold open he is the blank chained under Pat's floor, and his apology comes up through the locked door. Not Alan; whether he is also the blank Danny and Jodie rescue in episode five has not been supplied.", ["Content", "Helpful", "Unfazed"], "sand"],
];

export const characters = cast.map(([key, name, role, age, description, traits, color, sheet]) => ({
  id: characterId(key), name, role, age, description, traits, color, createdAt,
  ...(sheet ? { image: `/images/rapture/sheets/${sheet}.jpg` } : {}),
  relations: [],
}));
const reverse = { Parent: "Child", Child: "Parent", Colleague: "Colleague" };
function link(a, b, kind, note) {
  characters.find(c => c.id === characterId(a)).relations.push({ id: `rapture-link-${a}-${b}`, targetId: characterId(b), kind, note });
  characters.find(c => c.id === characterId(b)).relations.push({ id: `rapture-link-${b}-${a}`, targetId: characterId(a), kind: reverse[kind], note });
}
link("danny", "jodie", "Child", "Father and daughter scavenging for water; rules versus practical experience.");
link("martin", "max", "Child", "Martin cannot reach his son; Max borrowed the terminal for a poster.");
link("nina", "absconder", "Parent", "Nina never knew her father; the pendant was the terminal's tracker.");
link("kath", "ray", "Colleague", "Each thinks the other gets carried away.");
link("brenda", "gordon", "Colleague", "Thirty years behind the desk, no records on anyone.");
link("vassago", "reek", "Colleague", "Hell's intake floor.");
link("vassago", "tamsin", "Colleague", "He adopts her stolen-queue theory immediately.");
link("reek", "tamsin", "Colleague", "Investigating the wrong thing together.");
link("angel-one", "angel-two", "Colleague", "Recover the missing equipment.");
link("pat", "malcolm", "Colleague", "Keep the blank chained under the floor; they argue about method and neither learns anything.");

// Titles, working running times and on-camera cast for the thirteen numbered source shots.
// Durations are editorial estimates, NEVER the duration of just the written pause.
export const shotPlan = [
  { title: "The headlight switch", duration: 5, characters: [], image: "01-switch.jpg", note: "CU replaces the superseded WS. Headlight state is conveyed by the switch; no white beam is shown. Danny's hand only." },
  { title: "Rule two", duration: 15, characters: ["danny", "jodie"], image: "02-card.jpg", note: "Inside the cab, not the cops' bonnet-mounted two-shot. Small red dashboard practical only." },
  { title: "It's very cold", duration: 15, characters: ["danny"], image: "03-knocks.jpg", note: "Three knocks, then the full 3-second and 2-second pauses. Jodie stays off camera." },
  { title: "Mid-sentence", duration: 10, characters: ["woman-fourteen"], image: "04-mid-sentence.jpg", note: "Door swing and reopening occur within this setup. No listener, shadow-person or reaction insert." },
  { title: "Six places", duration: 10, characters: ["woman-fourteen", "danny"], image: "05-six-places.jpg", note: "Over the woman's shoulder without changing the source's MS designation. Table remains an unremarked cropped background detail; never show a whole room." },
  { title: "Tuesday was Thursday", duration: 23, characters: ["woman-fourteen", "danny"], image: "06-six-cups.jpg", note: "Six cups. Kettle indicator and letterbox spill only. Upstairs is intermittently dead locally, not yet the episode-five system-wide milestone." },
  { title: "Brown, then clear", duration: 11, characters: [], image: "07-brown-water.jpg", note: "Only the tap is on camera. Hold brown water for four full seconds before it clears. All three lines are off camera." },
  { title: "Rule one is biscuit", duration: 11, characters: ["jodie", "woman-fourteen"], image: "08-biscuit-rule.jpg", note: "Danny's line is off camera. No reaction cut." },
  { title: "No pocket", duration: 25, characters: ["danny"], image: "09-no-pocket.jpg", note: "Dedicated CU: Danny, the card and the pocketless jacket, with Jodie's hand entering frame holding the biscuit. Keep the slow blink and both 2-second pauses in one setup. Check card legibility and jacket-pocket continuity before approving." },
  { title: "The pipes", duration: 22, characters: ["jodie", "woman-fourteen"], image: "10-the-pipes.jpg", note: "Dedicated biscuit/bottle handover keyframe at the sink. Bottle returned full, cold, no air gap; no magical flash. Danny is off camera. Check the bottle fill line before approving." },
  { title: "About the council", duration: 13, characters: ["danny", "jodie"], image: "11-council.jpg", note: "Inside the moving cab. Vehicle exterior lights off. No reflective ending or grief." },
  { title: "The light stays on", duration: 5, characters: [], image: "12-passing-door.jpg", note: "MS replaces the superseded WS. Only a passing van panel and a slice of door, never a street establishing shot. No exterior van lights." },
  { title: "The unfinished complaint", duration: 10, characters: ["woman-fourteen"], image: "13-complaint.jpg", note: "Final mid-complaint pose at the door, from the street. No listener is revealed. The door closes after the 2-second pause, then a hard CUT TO BLACK, not a fade. Check door colour against shot 4 and keep red the only practical before approving." },
];

// Titles, working running times and setups for the seventeen numbered source shots of the
// episode-four scout hut: the scene after the violence. All handheld; the hi-vis MAN and the
// WOMAN who once did a course are unnamed group members, not cast entities, like the dog.
export const scoutHutPlan = [
  { title: "Four bottles", duration: 6, characters: ["danny", "jodie"], image: "01-doorway.jpg", shotType: "Medium", lens: "35mm", note: "The doorway. Danny and Jodie come in with four full bottles between them; Jodie is carrying three of them." },
  { title: "Twelve litre", duration: 14, characters: ["danny", "jodie"], image: "02-clipboard.jpg", shotType: "Medium close-up", lens: "28mm", note: "The hi-vis MAN with the clipboard is on them immediately. Twelve litre, genuinely impressive. Danny promises more coming tomorrow before he has decided it." },
  { title: "He said it first", duration: 6, characters: ["danny", "jodie"], image: "03-jodie-look.jpg", shotType: "Close-up", lens: "50mm", note: "On Jodie. She looks at her father. He said it before he'd decided it." },
  { title: "Nobody asks where from", duration: 8, characters: ["danny", "jodie"], image: "04-table.jpg", shotType: "Medium", lens: "35mm", note: "People come to the table. The bottles go. Somebody says well done. Nobody asks where from." },
  { title: "The sleeve is stuck", duration: 8, characters: ["danny"], image: "05-camp-bed.jpg", shotType: "Medium", lens: "28mm", note: "A corner of the hut. Danny sits on a camp bed and gets his coat off with difficulty. The sleeve is stuck to his arm." },
  { title: "Four puncture wounds", duration: 4, characters: [], image: "06-bandage.jpg", shotType: "Insert", lens: "85mm", note: "Insert, red light: the bandage. Soaked through. Four puncture wounds in a neat row." },
  { title: "Window frame", duration: 14, characters: ["danny", "jodie"], image: "07-window-frame.jpg", shotType: "Close-up", lens: "50mm", note: "On Jodie with the first aid kit, not squeamish, already working out that four holes in a row is going to need explaining. Window frame, twice, with no elaboration." },
  { title: "An extravagant thing", duration: 6, characters: ["danny", "jodie"], image: "08-cleaning.jpg", shotType: "Medium", lens: "35mm", note: "She cleans it with bottled water, which is now an extravagant thing to do, and both of them know it." },
  { title: "Who taught you that", duration: 10, characters: ["danny", "jodie"], image: "09-taught.jpg", shotType: "Close-up", lens: "50mm", note: "On Danny. He watches her do it properly, tightly, the way someone's shown her. You did. Did I? No." },
  { title: "Once did a course", duration: 8, characters: ["danny", "jodie"], image: "10-the-woman.jpg", shotType: "Medium", lens: "28mm", note: "A WOMAN (40s) appears with a mug: the nearest thing this group has to a nurse, which is to say she once did a course." },
  { title: "Tell someone", duration: 16, characters: ["danny", "jodie"], image: "11-antibiotics.jpg", shotType: "Close-up", lens: "50mm", note: "On the WOMAN. She looks at four punctures in a row, looks at Danny, and says nothing about it. Keep it clean; if it goes red up the arm, tell someone. And then what? Tell someone." },
  { title: "The rota argument", duration: 10, characters: ["danny"], image: "12-hut-carries-on.jpg", shotType: "Medium", lens: "35mm", note: "Wider. She goes. Danny sits with his arm out. The hut carries on around him: the kettle, the rota, an argument about the rota." },
  { title: "She leaves them by the gate", duration: 16, characters: ["danny", "jodie"], image: "13-by-the-gate.jpg", shotType: "Two-shot", lens: "50mm", note: "Very close two-shot, quiet. A long untimed pause; he doesn't have a lie ready. She leaves them by the gate." },
  { title: "She likes me", duration: 12, characters: ["danny", "jodie"], image: "14-she-likes-me.jpg", shotType: "Close-up", lens: "50mm", note: "On Jodie. Eleven years old, working out that her father has entered into an arrangement with the thing that stabbed him, and that it's the right decision. She does though." },
  { title: "Tea money", duration: 8, characters: ["danny"], image: "15-the-hut.jpg", shotType: "Medium", lens: "35mm", note: "He doesn't answer. He looks at the hut. Twenty-odd people drinking tea made from water he got by being stabbed." },
  { title: "Not in his handwriting", duration: 5, characters: [], image: "16-rota.jpg", shotType: "Insert", lens: "85mm", note: "Insert: the rota on the wall. Someone has written DANNY in the WATER column for tomorrow. Not in his handwriting." },
  { title: "Hold — cut", duration: 8, characters: ["danny", "jodie"], image: "17-hold.jpg", shotType: "Wide", lens: "28mm", note: "Red light, the hut, the one deliberate wide the grammar allows because it is handheld: him on the camp bed with his arm out, her packing the first aid kit away neatly. Hold. CUT." },
];

// Titles, working running times and setups for the sixteen numbered source shots of the
// episode-four cold open: Pat and Malcolm keeping house at dusk while a blank is chained
// under the floor. The light goes from dusk to dark across the timecodes; only the
// ten-second holds in shots 1 and 11 and the twelve-second hold in shot 14 are locked.
export const patColdOpenPlan = [
  { title: "Standing in the dark", duration: 14, characters: ["pat"], image: "01-standing-dark.jpg", shotType: "Medium", angle: "High angle", camera: "high corner", timecode: "16:12:04", lighting: "Low key", note: "A pensioner's front room in the dark at dusk. Curtains shut. Every surface immaculate. Pat stands in the middle of the room facing the fireplace, perfectly still. The ten-second hold is locked: she does not move at all." },
  { title: "Curtains open", duration: 8, characters: ["pat"], image: "02-curtains-open.jpg", shotType: "Medium", angle: "High angle", camera: "opposite high corner", timecode: "17:40:19", lighting: "Blue hour", note: "The curtains are open now and the dusk is failing at the window. Same position, same stance." },
  { title: "Three different men", duration: 6, characters: [], image: "03-photographs.jpg", shotType: "Insert", angle: "Eye level", camera: "the sideboard", lighting: "Blue hour", note: "Fixed insert on the sideboard: a row of framed photographs. The same woman in all of them. Three different men." },
  { title: "The sweet tin", duration: 12, characters: ["pat"], image: "04-sweet-tin.jpg", shotType: "Medium", angle: "High angle", camera: "high corner, the kitchen", lighting: "Blue hour", note: "She takes down the sweet tin. Empty. She tips in a bag of boiled sweets, then another, and another. Only boiled sweets, nothing else, and she levels the top with her hand so they sit flat." },
  { title: "The cupboard of water", duration: 8, characters: ["pat"], image: "05-water-cupboard.jpg", shotType: "Medium", angle: "High angle", camera: "the kitchen, opposite angle", lighting: "Blue hour", note: "She opens the next cupboard along: slabs of bottled water, floor to shelf, dozens of them. Not bait — just a demon who doesn't drink, sitting on the most valuable thing in the county for no reason. She looks at them for a moment. Closes the cupboard." },
  { title: "Up out of the cellar", duration: 10, characters: ["malcolm"], image: "06-cellar-door.jpg", shotType: "Medium", angle: "High angle", camera: "high corner, the hall", lighting: "Practical night", note: "The door under the stairs opens. Malcolm comes up out of it, closes it behind him and turns a key. The blank is planted before anyone knocks." },
  { title: "Up to the elbow", duration: 10, characters: ["pat", "malcolm"], image: "07-elbow-wash.jpg", shotType: "Medium", angle: "High angle", camera: "the kitchen", lighting: "Practical night", note: "He washes his hands at the sink. Thoroughly. Up to the elbow. She asks Anything? and gets He's apologised again." },
  { title: "Square on the hook", duration: 12, characters: ["pat", "malcolm"], image: "08-tea-towel.jpg", shotType: "Medium", angle: "High angle", camera: "high corner, kitchen, wide", lighting: "Practical night", note: "He dries his hands and hangs the tea towel back on its hook, square. The argument about method is the entire demon plot in eight lines: she's right, he can't accept it, neither will learn anything." },
  { title: "Doilies", duration: 8, characters: ["pat"], image: "09-doilies.jpg", shotType: "Medium", angle: "High angle", camera: "high corner, the front room", lighting: "Practical night", note: "Pat sits in the armchair, squares the doilies on the arms, then adds another doily to a table that already has one on it." },
  { title: "Hand on the key", duration: 10, characters: ["malcolm"], image: "10-hand-on-key.jpg", shotType: "Medium", angle: "Eye level", camera: "the hall", lighting: "Practical night", note: "Malcolm at the cellar door with his hand on the key. He doesn't go back down. He doesn't walk away either." },
  { title: "I can only apologise", duration: 14, characters: ["graham"], image: "11-the-voice.jpg", shotType: "Medium", angle: "Low angle", camera: "fixed on the cellar door, low angle, fisheyed", lighting: "Low key", note: "Held. The ten-second hold is locked. From behind the door, muffled, entirely calm and pleasant: Graham — the blank Hell interviewed in episode three — apologising in the intonation of a man doing what he's told. The phrase's worst use so far, arriving from behind a locked door. He is heard, never seen." },
  { title: "Off the key", duration: 6, characters: ["malcolm"], image: "12-off-the-key.jpg", shotType: "Medium", angle: "Eye level", camera: "the hall", lighting: "Practical night", note: "Malcolm's hand on the key. He takes it off the key." },
  { title: "Facing the window", duration: 8, characters: ["pat"], image: "13-armchair.jpg", shotType: "Medium", angle: "High angle", camera: "high corner, the front room", lighting: "Practical night", note: "Pat in the armchair, facing the window, hands on the arms of the chair. Perfectly still. The street outside is dark now." },
  { title: "The smile", duration: 16, characters: ["pat"], image: "14-the-smile.jpg", shotType: "Medium", angle: "High angle", camera: "held", timecode: "19:51:32", lighting: "Low key", note: "Hold. The twelve-second hold is locked: nothing moves in the frame at all. Then, without any change in her posture, she smiles at the window. There is nobody at the window." },
  { title: "Nobody comes", duration: 5, characters: [], image: "15-the-window.jpg", shotType: "Insert", angle: "Eye level", camera: "the window, from inside", lighting: "Practical night", note: "Fixed insert from inside: an empty front path, a gate, a street in the dark. Nobody comes." },
  { title: "Black — title card", duration: 4, characters: [], image: "16-black.jpg", shotType: "Insert", angle: "Eye level", camera: "black", lighting: "Low key", note: "Black. Title card. The burnt-in timecode is the only thing that has kept the dusk honestly." },
];

export const patHouseSceneId = "rapture-ep4-pat";
export const patHouseFrontGrammar = "Pat's grammar: lamplit, warm, flat, frontal, static, tidy. Locked off and dead centre; the camera never moves; doilies on everything. Dry, deadpan British black comedy; no score, no stings.";
export const patHouseTwoGrammar = "Two grammars in one house, never blended within a shot. Front room: lamplit, warm, flat, frontal, static, tidy — hers. Kitchen and garden: handheld, close, dark, red torchlight — Danny and Jodie's. The cut between rooms is a cut between two different programmes. Shots 31-32 switch to fixed high-corner 4:3 surveillance with burnt-in timecode; shots 33-35 snap back to the Crane grammar, abruptly.";

// Titles, working running times and setups for the thirty-five numbered source shots of
// episode four Scene 2: the old-lady sequence, now numbered. g marks the grammar of each
// shot: front (Pat's static lamplit programme), crane (tight red handheld) or demon
// (fixed surveillance). Source lenses outside the library map to the closest option and
// stay in the notes.
export const patHousePlan = [
  { title: "Squash and doilies", duration: 14, characters: ["pat", "jodie"], image: "01-settee-squash.jpg", shotType: "Wide", lens: "35mm", lensSource: "32mm", movement: "Static", angle: "Eye level", lighting: "Blue hour", g: "front", note: "Immaculate. Two table lamps on, curtains not yet drawn, the window going blue behind. Doilies on everything, including things that cannot take a doily. Jodie on the settee with a glass of squash; Pat opposite, delighted." },
  { title: "Only boiled sweets", duration: 5, characters: [], image: "02-sweet-tin-offered.jpg", shotType: "Insert", lens: "85mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "The sweet tin, open, offered. Only boiled sweets. Levelled flat." },
  { title: "Free sweets are free sweets", duration: 6, characters: ["jodie"], image: "03-jodie-takes-one.jpg", shotType: "Medium", lens: "50mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Jodie takes one. She's eleven. Free sweets are free sweets." },
  { title: "He cannot believe his luck", duration: 10, characters: ["danny"], image: "04-water-cupboard-torch.jpg", shotType: "Close-up", lens: "24mm", lensSource: "28mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "Unlit kitchen. Danny goes through cupboards by torch, silent. He opens one: slabs of bottled water, floor to shelf. He cannot believe his luck." },
  { title: "Does he take things", duration: 16, characters: ["pat", "jodie"], image: "05-does-he-take-things.jpg", shotType: "Two-shot", lens: "35mm", lensSource: "40mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "The audit continues over the squash. Not off anyone who's still alive. Won't he." },
  { title: "Fascinated by the data", duration: 12, characters: ["pat"], image: "06-rouge-data.jpg", shotType: "Close-up", lens: "50mm", lensSource: "65mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Lamplight on too much rouge. Fascinated. Not by the child. By the data. The old scout hut off the bypass; twenty-something of them." },
  { title: "Malcolm's the other one", duration: 10, characters: ["pat", "jodie"], image: "07-wedding-photo.jpg", shotType: "Insert", lens: "85mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "A framed wedding photograph on the sideboard. The man's face is slightly wrong, like it was added later. That's my Derek. You said Malcolm. No pause whatsoever: Malcolm's the other one." },
  { title: "Old people are confusing", duration: 6, characters: ["jodie"], image: "08-old-people-confusing.jpg", shotType: "Medium", lens: "50mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Jodie accepts this. She's eleven and old people are confusing." },
  { title: "The handles strain", duration: 8, characters: ["danny"], image: "09-bottles-in-bag.jpg", shotType: "Medium", lens: "35mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "Bottles into a bag. Too many. The handles strain. The torch clamped under his chin." },
  { title: "The mug", duration: 8, characters: ["danny"], image: "10-the-mug.jpg", shotType: "Medium", lens: "24mm", lensSource: "28mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "He turns and knocks a mug off the draining board. It hits the lino. It doesn't break. In a silent house it is enormous." },
  { title: "Mid-word", duration: 8, characters: ["pat", "jodie"], image: "11-mid-word.jpg", shotType: "Two-shot", lens: "35mm", lensSource: "40mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Pat stops. Mid-word. Nothing on her face changes. She stands up and walks out of the room. She does not excuse herself." },
  { title: "Alone with the squash", duration: 8, characters: ["jodie"], image: "12-jodie-alone.jpg", shotType: "Medium", lens: "50mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Jodie alone in a lamplit room with a glass of squash, looking at an empty chair." },
  { title: "You gave me a fright", duration: 10, characters: ["danny", "pat"], image: "13-backlit-shape.jpg", shotType: "Medium", lens: "35mm", movement: "Handheld", angle: "Eye level", lighting: "Backlit silhouette", g: "crane", note: "Danny frozen, bag in hand, torch beam on the floor. The hall light comes on behind Pat as she enters — she's backlit, shape only. Warm, apologetic: oh — you gave me a fright." },
  { title: "I — the door was —", duration: 6, characters: ["danny"], image: "14-danny-explains.jpg", shotType: "Close-up", lens: "50mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "He starts an explanation. He has nothing." },
  { title: "Too wide", duration: 10, characters: ["pat"], image: "15-too-wide.jpg", shotType: "Close-up", lens: "50mm", lensSource: "65mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "His torch comes up onto her face. Still the old lady: cardigan, rouge, concerned expression. Then the mouth opens too wide, jaw unhinged past anything a face should do; the eyes go black, cornea to cornea. Everything else about her is unchanged. Storyboard-flat, no gore." },
  { title: "Two steps", duration: 6, characters: ["pat", "danny"], image: "16-two-steps.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "She crosses the kitchen in two steps. Faster than a person. Much faster than a pensioner. Torch swinging, chaotic." },
  { title: "Held like cutlery", duration: 5, characters: ["pat"], image: "17-knife-and-fork.jpg", shotType: "Insert", lens: "85mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "Her hands in the torchlight. A knife in one, a fork in the other, out of her own drawer, held the way you hold cutlery at a table." },
  { title: "The rhythm of a meal", duration: 10, characters: ["pat", "danny"], image: "18-eating-rhythm.jpg", shotType: "Medium", lens: "35mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "She's on him. Both arms going up and down, alternating, knife and fork, over and over — the exact rhythm of someone eating a meal. The torch on the floor only lighting the ceiling. Silent. No shriek, no roar. Nothing." },
  { title: "Through the window", duration: 6, characters: ["danny"], image: "19-through-the-window.jpg", shotType: "Medium", lens: "24mm", lensSource: "28mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "Danny gets the window over the sink open and goes through, half falling, half throwing himself." },
  { title: "The fork", duration: 5, characters: ["danny"], image: "20-fork-forearm.jpg", shotType: "Insert", lens: "85mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "The fork goes through his forearm on the way out. It stays in for a second. It comes out with him. Blood black in torchlight, no gore spectacle." },
  { title: "He never let go", duration: 8, characters: ["danny"], image: "21-flowerbed.jpg", shotType: "Medium", lens: "35mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "He lands in a flowerbed. Gets up. The bag of water is still in his other hand. He never let go of it." },
  { title: "Over the fence", duration: 6, characters: ["danny"], image: "22-over-the-fence.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "Over the fence, badly. Blood down his sleeve, black in this light." },
  { title: "Bottles by the gate", duration: 8, characters: ["pat"], image: "23-bottles-by-the-gate.jpg", shotType: "Medium", lens: "50mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Her grammar returns. Pat at the open window, lit from the hall behind her. Face entirely normal. Cardigan straight. She calls out into the dark in the voice she was using in the front room: I'll leave the bottles by the gate, love." },
  { title: "Brown water", duration: 8, characters: ["pat"], image: "24-brown-water.jpg", shotType: "Insert", lens: "85mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "She puts the knife and fork in the sink. Runs the tap over them. The water comes out brown. She lets it run anyway." },
  { title: "Resumes exactly", duration: 8, characters: ["pat", "jodie"], image: "25-resumes.jpg", shotType: "Two-shot", lens: "35mm", lensSource: "40mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Pat comes back in, sits down, picks up her tea, and resumes exactly where she left off: — because Derek never liked the bypass." },
  { title: "What happens if she gets it wrong", duration: 10, characters: ["jodie"], image: "26-jodie-works-it-out.jpg", shotType: "Medium", lens: "50mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Eleven years old. Glass of squash. She heard the window. She heard the line about the bottles. She has worked out precisely what is happening and precisely what happens if she gets it wrong." },
  { title: "Another sweet", duration: 10, characters: ["pat", "jodie"], image: "27-another-sweet.jpg", shotType: "Two-shot", lens: "35mm", lensSource: "40mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Another sweet? No thank you. Go on. Thank you." },
  { title: "The glass on a doily", duration: 12, characters: ["pat", "jodie"], image: "28-glass-on-doily.jpg", shotType: "Wide", lens: "35mm", lensSource: "32mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Same framing as shot 1. Jodie stands, puts her glass on a doily; Pat watches her do it. The window behind them is dark now. Will you come again? Probably. Good." },
  { title: "The door under the stairs", duration: 10, characters: ["jodie"], image: "29-the-hall.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Jodie walks to the front door. A long hall, lit by one bulb. Pat doesn't get up. Jodie passes the door under the stairs. She doesn't look at it. She lets herself out." },
  { title: "Doesn't run", duration: 10, characters: ["jodie"], image: "30-down-the-path.jpg", shotType: "Wide", lens: "35mm", movement: "Static", angle: "Eye level", lighting: "Practical night", g: "front", note: "Still her grammar, not theirs. Jodie walks down the path at a completely normal pace, out of the light from the hall and into the dark. Through the gate. Doesn't run. Doesn't look back." },
  { title: "Malcolm comes up", duration: 8, characters: ["malcolm"], image: "31-malcolm-up.jpg", shotType: "Medium", lens: "24mm", movement: "Static", angle: "High angle", lighting: "Practical night", g: "demon", camera: "high corner", note: "Demon grammar. The cellar door opens. Malcolm comes up. Turns the key behind him." },
  { title: "Where's the water gone", duration: 14, characters: ["malcolm", "pat"], image: "32-where-water-gone.jpg", shotType: "Medium", lens: "24mm", movement: "Static", angle: "High angle", lighting: "Practical night", g: "demon", camera: "the kitchen, high corner", note: "He stops. The window is open to the dark. A mug on the lino. A fork in the sink. He looks at the water cupboard; the door is ajar. Where's the water gone? Pause. I've made a friend." },
  { title: "She's leaving the rest by the gate", duration: 10, characters: ["danny", "jodie"], image: "33-round-the-corner.jpg", shotType: "Medium", lens: "35mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "Their grammar, abruptly. Jodie rounds the corner. Danny's against a wall, white, holding his arm, bag at his feet. We're not coming back here. She's leaving the rest by the gate." },
  { title: "Going back", duration: 6, characters: ["danny"], image: "34-going-back.jpg", shotType: "Close-up", lens: "50mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "A man who is bleeding and has just understood he is going to come back." },
  { title: "She's carrying the bag", duration: 8, characters: ["danny", "jodie"], image: "35-walking-away.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", movement: "Handheld", angle: "Eye level", lighting: "Practical night", g: "crane", note: "The two of them walking away into the dark. She's carrying the bag. He isn't. Hold." },
];

// Titles, working running times and setups for the fifteen numbered source shots of the
// episode-three cold open: the recovery angels' first appearance. Durations are editorial
// estimates; only the eight-second pause in shot 1 is a locked written pause. Source lenses
// outside the app's library map to the closest option and stay in the notes. The unnamed MAN
// (60s, cardigan) in the garden centre is a blank who joins no cast list, like the dog.
export const ep3ColdOpenPlan = [
  { title: "Where would you keep a computer", duration: 14, characters: ["angel-one", "angel-two"], image: "01-park.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", lighting: "Golden hour", note: "An empty municipal park, a bandstand, dead centre, golden light. The pair stand in the middle of the grass, perfectly composed, facing the same direction, and have been there for some time. The eight-second pause is locked." },
  { title: "The report", duration: 14, characters: ["angel-one", "angel-two"], image: "02-symmetrical.jpg", shotType: "Wide", lens: "24mm", lighting: "Golden hour", note: "Centred, the bandstand exactly behind them. Neither has read the report, and neither mind is remotely troubled by this." },
  { title: "It's beige", duration: 8, characters: ["angel-one", "angel-two"], image: "03-frontal.jpg", shotType: "Medium", lens: "50mm", lighting: "Golden hour", note: "Frontal locked-off two-shot. Both facing camera. Nothing behind the eyes, but well-lit. Beige is the main thing about it." },
  { title: "In perfect step", duration: 8, characters: ["angel-one", "angel-two"], image: "04-high-street.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", lighting: "Golden hour", note: "An empty high street. They walk down the middle of it in perfect step past broken glass, an overturned bin and a dog in a doorway; none of it is looked at." },
  { title: "The window", duration: 6, characters: ["angel-one", "angel-two"], image: "05-shop-window.jpg", shotType: "Wide", lens: "24mm", lighting: "Golden hour", note: "They stop outside a shop and look in the window. Centred, lovely light." },
  { title: "Beige garden furniture", duration: 3, characters: [], image: "06-beige-display.jpg", shotType: "Insert", lens: "85mm", lighting: "Golden hour", note: "Insert: a window display of beige garden furniture. Immaculate." },
  { title: "Not that sort of beige", duration: 6, characters: ["angel-one", "angel-two"], image: "07-not-that-beige.jpg", shotType: "Medium", lens: "50mm", lighting: "Golden hour", note: "Frontal. Soqed's quiet beige to himself, and Hariel's correction." },
  { title: "The centre aisle", duration: 8, characters: ["angel-one", "angel-two"], image: "08-centre-aisle.jpg", shotType: "Wide", lens: "24mm", lighting: "High key", note: "A garden centre: enormous, empty, strip-lit, racks of compost. Deep perspective down the centre aisle, still in step." },
  { title: "A man between the pallets", duration: 8, characters: ["angel-one", "angel-two"], image: "09-the-blank.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", lighting: "High key", note: "They stop. In the middle distance, standing between two pallets of bark chippings, facing nothing: a MAN (60s, cardigan, still). Unnamed by the source; he joins no cast list." },
  { title: "Ours or theirs", duration: 12, characters: ["angel-one", "angel-two"], image: "10-ours-or-theirs.jpg", shotType: "Medium", lens: "50mm", lighting: "High key", note: "Frontal on the two angels. He's nobody's, everyone's using them, that's what they're for." },
  { title: "Neither approaches", duration: 6, characters: ["angel-one", "angel-two"], image: "11-no-approach.jpg", shotType: "Wide", lens: "24mm", lensSource: "28mm", lighting: "High key", note: "The blank continues facing nothing. Neither angel approaches him." },
  { title: "The blank's eyes", duration: 4, characters: [], image: "12-eyes.jpg", shotType: "Insert", lens: "85mm", lighting: "High key", note: "Insert: the blank's eyes. Nothing wrong with them. Nothing behind them either." },
  { title: "Because they haven't", duration: 14, characters: ["angel-one", "angel-two"], image: "13-the-plan.jpg", shotType: "Two-shot", lens: "50mm", lighting: "High key", note: "Frontal two-shot. Locate the equipment, recover the equipment, go home; the permissions are the whole argument, delivered with total confidence." },
  { title: "The wrong direction", duration: 10, characters: ["angel-one", "angel-two"], image: "14-wrong-direction.jpg", shotType: "Wide", lens: "24mm", lighting: "High key", note: "They walk away down the centre aisle, in step, immaculate, past the motionless man, in entirely the wrong direction. Hold." },
  { title: "Black — title card", duration: 4, characters: [], image: "15-black.jpg", shotType: "Insert", lighting: "Low key", note: "Black. Title card. No timecode burn-in; that grammar belongs to Hell." },
];

// Titles, working running times and on-camera cast for the seventeen numbered source shots of
// the episode-four cold open. Durations are editorial estimates; only the written pauses
// (the six-second pause in shot 3, the twelve-second hold in shot 15) are locked. The timecode
// values in the source do the comedy's heavy lifting and are reproduced verbatim in the notes.
export const coldOpenPlan = [
  { title: "Where did they go", duration: 14, characters: ["reek", "tamsin", "graham"], image: "01-room.jpg", shotType: "Medium", angle: "High angle", camera: "high corner", timecode: "11:04:22", note: "Establishing fixed angle of the front room. Graham content in the armchair, hands on knees, facing slightly away; Reek and Tamsin too upright on the settee, like people who have been told how chairs work." },
  { title: "The pen", duration: 12, characters: ["reek", "tamsin", "graham"], image: "02-folder.jpg", shotType: "Medium", angle: "High angle", camera: "opposite high corner", timecode: "11:19:51", note: "Reverse fixed angle. Tamsin's folder open on her knee; the rollerball of 1998 goes in the record. Same positions, no blocking change." },
  { title: "Look at me", duration: 18, characters: ["reek", "tamsin", "graham"], image: "03-look-at-me.jpg", shotType: "Medium", angle: "High angle", camera: "high corner", timecode: "11:41:07", note: "Reek stands over Graham and does something demonic and enormous with his face and voice; the cheap camera flattens it. The six-second pause is locked, then Graham offers a drink. Tamsin keeps writing throughout." },
  { title: "He might be being clever", duration: 10, characters: ["reek", "tamsin"], image: "04-doorway.jpg", shotType: "Medium", angle: "High angle", camera: "the doorway", timecode: "11:52:30", note: "A different fixed angle from the hall doorway. Graham absent making drinks; Reek and Tamsin stand in the middle of the room, not touching anything." },
  { title: "Three mugs", duration: 12, characters: ["reek", "tamsin", "graham"], image: "05-three-mugs.jpg", shotType: "Medium", angle: "High angle", camera: "high corner", timecode: "12:08:14", note: "All three seated again. Three mugs on the coffee table; nobody has touched theirs. Are you dead / I'd have heard." },
  { title: "Wales?", duration: 16, characters: ["reek", "tamsin", "graham"], image: "06-light-changed.jpg", shotType: "Medium", angle: "High angle", camera: "opposite corner", timecode: "13:26:48", note: "The light in the room has changed and nobody has moved. Graham's guess, delivered helpfully, is Wales. No reaction from anyone but Tamsin, and that only in shot 7." },
  { title: "WALES, underlined", duration: 4, characters: ["tamsin"], image: "07-wales.jpg", shotType: "Insert", angle: "High angle", camera: "on the folder", note: "Fixed insert on Tamsin's folder: she writes WALES and underlines it. The single most important document of the investigation." },
  { title: "Payroll", duration: 16, characters: ["reek", "tamsin", "graham"], image: "08-floor.jpg", shotType: "Medium", angle: "High angle", camera: "high corner", timecode: "14:02:33", note: "Reek has given up on furniture and sits on the floor with his back against the wall. Tamsin is still going. Graham is at his most animated: the wages, but the deductions as well." },
  { title: "Salary sacrifice", duration: 6, characters: ["reek", "tamsin", "graham"], image: "09-payroll.jpg", shotType: "Medium", angle: "High angle", camera: "opposite corner", timecode: "14:47:19", note: "Graham is still talking. Reek's head is tipped back against the wall; Tamsin's pen has stopped." },
  { title: "Come unstuck", duration: 6, characters: ["reek", "tamsin", "graham"], image: "10-wide-still.jpg", shotType: "Wide", angle: "High angle", camera: "a wide fixed angle", timecode: "15:31:52", note: "The widest fixed angle. Nobody has moved, the mugs have gone cold, and the clause most firms come unstuck lands into total stillness. Shot 15 repeats it exactly." },
  { title: "Have you ever made a decision", duration: 10, characters: ["reek", "tamsin", "graham"], image: "11-exit.jpg", shotType: "Medium", angle: "High angle", camera: "high corner", timecode: "16:14:08", note: "Reek gets up and walks out of frame; a door goes. Tamsin remains, alone with Graham, and gets I can only apologise with no pause at all." },
  { title: "Writes it down", duration: 5, characters: ["tamsin"], image: "12-decision.jpg", shotType: "Medium", lens: "35mm", angle: "Eye level", camera: "on Tamsin", note: "Fixed angle on Tamsin. She looks at him, writes it down, and has no idea what it means." },
  { title: "He's not given us Wales", duration: 10, characters: ["reek", "tamsin"], image: "13-doorway-coat.jpg", shotType: "Medium", angle: "High angle", camera: "the doorway", note: "Fixed angle on the doorway: Reek back in the doorway, coat on. The only lead is defended." },
  { title: "Graham alone", duration: 8, characters: ["graham"], image: "14-alone.jpg", shotType: "Wide", angle: "High angle", camera: "high corner, wide", timecode: "16:14:08", note: "They leave; the front door goes. Graham, alone in his armchair, hands back on his knees. He does not get up, look round, or change the direction he was facing." },
  { title: "The glitch", duration: 15, characters: ["graham"], image: "15-glitch.jpg", shotType: "Wide", angle: "High angle", camera: "held", timecode: "16:15:47", note: "Hold. The twelve-second hold is locked, then — no sound, no cut — Graham says the next clause of his shot-10 sentence in exactly the same intonation. The first glitch the audience sees, played completely flat: no music sting, no camera move." },
  { title: "Held", duration: 6, characters: ["graham"], image: "16-held.jpg", shotType: "Wide", angle: "High angle", camera: "held", timecode: "16:21:05", note: "Nothing. The same held fixed angle; the timecode ticking is the only event." },
  { title: "Black — title card", duration: 4, characters: [], image: "17-black.jpg", shotType: "Insert", angle: "Eye level", camera: "black", lighting: "Low key", note: "Black. Title card. Only the burnt-in timecode confirms the tape never stopped." },
];

// Titles, working running times and on-camera cast for the first wrong lockup's
// numbered source shots. Durations are editorial estimates. The dog appears in
// several shots but is not a cast entity; shot 29's source ends mid-line.
export const lockupPlan = [
  { image: "01-minibus.jpg", title: "The minibus on the empty road", duration: 12, characters: [], note: "Long lens, heat shimmer. The bus takes a long time to reach mid-frame; Nina is inside but not seen." },
  { image: "02-dont-look.jpg", title: "Don't look at me", duration: 6, characters: ["nina"], note: "From the passenger side. The dog sits upright like a passenger." },
  { image: "03-church.jpg", title: "The church queue", duration: 10, characters: [], note: "Forty deep, trestle table, bad clipboard organisation, two men arguing. The bus doesn't slow." },
  { image: "04-roadblock.jpg", title: "The roadblock", duration: 10, characters: [], note: "Three wheelie bins, a garden bench, one boy with a cricket bat. Around it on the verge." },
  { image: "05-unbothered.jpg", title: "Unbothered", duration: 5, characters: ["nina"], note: "The dog watches the boy go past." },
  { image: "06-chosen.jpg", title: "We are the chosen ones", duration: 6, characters: [], note: "Footbridge sheets: WE ARE THE CHOSEN ONES over ROOMS AVAILABLE." },
  { image: "07-pendant.jpg", title: "The pendant", duration: 12, characters: ["nina"], note: "Pulls over, kills the engine, holds the pendant like it owes her money." },
  { image: "08-braced.jpg", title: "Braced", duration: 5, characters: ["nina"], note: "Not reverent — a dreaded phone call." },
  { image: "09-shutter.jpg", title: "Flash: the orange shutter", duration: 2, characters: [], lighting: "High key", note: "Vision footage: broken, wrong aspect, dropped frames, blown out, a hiss." },
  { image: "10-strips.jpg", title: "Flash: strip lights", duration: 2, characters: [], lighting: "High key", note: "One flickering." },
  { image: "11-bay.jpg", title: "Flash: the bay number", duration: 2, characters: [], lighting: "High key", note: "Two digits, held a beat too briefly to be certain." },
  { image: "12-carpet.jpg", title: "Flash: carpet and radiator", duration: 2, characters: [], lighting: "High key", angle: "Low angle", note: "Six inches off the floor. Wrong decade." },
  { image: "13-forty-one.jpg", title: "Forty-one, or forty-seven?", duration: 7, characters: ["nina"], note: "Eyes open, breathing hard, profoundly unimpressed." },
  { image: "14-right.jpg", title: "Right.", duration: 12, characters: ["nina"], note: "Untimed pause, repeated line, engine start." },
  { image: "15-estate.jpg", title: "The industrial estate", duration: 8, characters: [], note: "Low unit behind chain link. Not Martin's unit; similar enough. Barrier down, weeds." },
  { image: "16-cutters.jpg", title: "The bolt cutters", duration: 12, characters: ["nina"], note: "The gate chain dealt with in about nine seconds." },
  { image: "17-corridor.jpg", title: "The orange corridor", duration: 12, characters: ["nina"], note: "Orange roller doors to a vanishing point, one strip light flickering. She walks away down the middle. Same composition as Martin's corridor; wrong building." },
  { image: "18-forty-one.jpg", title: "Forty-one", duration: 12, characters: ["nina"], note: "Three padlock attempts." },
  { image: "19-chairs.jpg", title: "Four hundred garden chairs", duration: 6, characters: [], note: "Low: the shutter goes up on roughly four hundred plastic garden chairs." },
  { image: "20-chairs-look.jpg", title: "Nina looks at the chairs", duration: 5, characters: ["nina"], note: "Held on her taking it in." },
  { image: "21-forty-seven.jpg", title: "Forty-seven", duration: 10, characters: ["nina"], note: "Walks to 47. Cuts that padlock too." },
  { image: "22-empty.jpg", title: "Empty", duration: 6, characters: [], note: "Low: concrete floor and a dead wasp." },
  { image: "23-other-forty.jpg", title: "One of the other forty?", duration: 7, characters: ["nina"], note: "Upward, conversational." },
  { image: "24-long-corridor.jpg", title: "The long corridor", duration: 10, characters: ["nina"], note: "Same framing as 17. Her small at the far end. Hold." },
  { image: "25-back-bus.jpg", title: "Back at the bus", duration: 8, characters: ["nina"], note: "Loads the bolt cutters. Stops." },
  { image: "26-tuesday.jpg", title: "Here since Tuesday", duration: 30, characters: ["nina", "alan"], note: "The man by the bus, perfectly still, bag in hand. The full exchange, with an untimed pause." },
  { image: "27-bag.jpg", title: "Bag for life", duration: 12, characters: ["nina", "alan"], note: "On Nina. Twenty years of front-door assessments." },
  { image: "28-door.jpg", title: "The passenger door", duration: 10, characters: ["nina", "alan"], note: "She properly considers leaving him. Then opens the door." },
  { image: "29-name.jpg", title: "Name?", duration: 14, characters: ["nina", "alan"], note: "The full exchange, ending on I can only apologise. Interior; he sits upright like the dog." },
  { image: "30-engine.jpg", title: "Nothing registers", duration: 6, characters: ["nina"], note: "She has no idea what that means. She starts the engine." },
  { image: "31-away.jpg", title: "Pulling away", duration: 10, characters: [], note: "The bus, tiny, down a long straight road. Heat shimmer. Hold." },
];

// Planning outlines, not invented finished scripts. Locations/times are provisional except for explicit bible grammar.
export const outlinePlan = [
  [1, "mugging", "The mugging", "EXT. ALLEY", "NIGHT", [], "The mugging. The knife starts its journey through the old woman's handbag and the support group.", "Cold open"],
  [1, "st-judes", "St Jude's and the rapture", "INT. ST JUDE'S", "DAY", ["nina"], "Nina at St Jude's; the rapture. One ignored complaint about water pressure. Locked off, wide, deep focus, daylight, symmetrical."],
  [1, "washing-up", "Washing up", "INT./EXT. ST JUDE'S", "DAY", ["nina"], "Clearing the hall and collecting water around St Jude's. Nina's locked-off daylight grammar applies."],
  [1, "cops", "Birds, arrest ourselves, the taser", "INT. POLICE CAR", "DAY", ["kath", "ray"], "Birds; arrest ourselves; the taser. Static windscreen two-shot from the bonnet and a wide across the car park. Handheld only during violence, then identical static framing. No reaction cuts."],
  [1, "bearing", "The pendant and first vision", "INT./EXT. ST JUDE'S / ROAD", "DAY", ["nina"], "Nina's aftermath, the pendant, the first vision; she drives. The vision is the tracker's recorded view, not divine revelation. Only this interruption breaks Nina's grammar."],
  [1, "storage", "Martin at the storage unit", "INT. STORAGE UNIT", "DAY", ["martin"], "Martin at the storage unit. No mechanism revealed. Flat fluorescent light, locked off, slightly off-centre."],
  [1, "no", "1980 thread — NO", "INT. HOTEL ROOM", "NIGHT", ["absconder"], "Tag for the 1980 thread, ending on NO. Preserve the bible's five-years-later death chronology; do not silently date the hotel scene 1980. Warm, grainy anamorphic practical light.", "Tag"],
  [2, "limbo", "The family at the desk", "INT. LIMBO CATHEDRAL", "CONTINUOUS", ["brenda", "gordon"], "The family, branches of Christianity, seventy-two virgins, husband led away. Frontal proscenium, vast vertical space, hard cut to the flat close desk. Four-second reverberation."],
  [2, "raid", "The first raid", "INT. HOUSE", "NIGHT", ["danny", "jodie"], "Danny and Jodie's first raid for water. Handheld, tight and dark, red practical sources only. Never a whole room."],
  [2, "night-drive", "Night drive (Wave 3)", "EXT./INT. VAN / ROAD", "NIGHT", ["danny", "jodie"], "An earlier night-drive board for the Crane thread. Its horror framing and non-red night lighting are superseded, and its episode-two placement is provisional."],
  [2, "intake", "The intake floor", "INT. HELL INTAKE", "CONTINUOUS", ["vassago", "reek", "tamsin"], "Hell's intake collapse goes unnoticed behind balloon concerns. Fixed high-corner surveillance, 4:3, slight fisheye, faint timecode. Never close."],
  [3, "arrivals", "Both sides come down", "EXT. EARTH — LOCATION TBC", "DAY", ["angel-one", "angel-two", "pat", "field-officer"], "Demons and angels arrive, badly. Keep faction coverage separate; no invented shared scene. Demons retain fixed surveillance grammar on earth."],
  [3, "test", "A worthless screening method", "INT. POLICE CAR", "DAY", ["kath", "ray"], "Blanks established. The cops invent a test around I can only apologise and never doubt it. Half of real humanity says it too."],
  [3, "group", "Recruited / brown water", "INT. UNDERGROUND MEETING PLACE", "NIGHT", ["danny", "jodie"], "Danny and Jodie recruited by the underground group. Brown water. Tight red practical handheld coverage; no full-room tableau."],
  [3, "home", "A collection and no son", "INT. MARTIN'S HOME", "DAY", ["martin"], "Martin comes home to a collection and no son. Aggrieved, not grieving. Flat, fluorescent, off-centre."],
  [4, "meetings", "Survivors' meetings", "INT. MEETING PLACE", "DAY", [], "Grandma and the dog are reported as proof they are here to maintain order. Someone mentions a nun. No mechanism explanation or catch-up scene."],
  [5, "basement", "The interrogation", "INT. CELLAR", "NIGHT", ["field-officer", "rescued-blank"], "The chained blank. The interrogation goes nowhere. The officer has notes and thinks she is close. Fixed high-corner surveillance, never close; the violence is not spectacular."],
  [5, "rescue", "Laminate flooring", "INT. CELLAR / EXIT", "NIGHT", ["danny", "jodie", "rescued-blank"], "Danny and Jodie rescue the man who talks about laminate flooring. Hell is watching through him. Upstairs taps are dead. The Crane coverage remains tight red handheld."],
  [5, "scent", "The cops pick up Danny's scent", "INT. POLICE CAR", "DAY", ["kath", "ray"], "Property-law enforcement over water scavenging. Static windscreen two-shot; wrong details pursued sincerely."],
  [5, "misspelling", "RAPTURES", "INT. MAX'S ROOM", "DAY", ["max"], "Max flashback: the misspelling of The Raptors. He is alive and unreachable, not a present-day participant.", "Flashback"],
  [6, "dry", "The taps fail", "INT. MEETING PLACE", "NIGHT", ["danny", "jodie"], "Dry taps. The group turns on itself; a moment of clarity. The apocalypse as a maintenance backlog, never a tragic performance."],
  [6, "saint", "A bearing that isn't wrong", "EXT. ROAD", "DAY", ["nina", "alan"], "Nina gets a correct bearing and is found by people who have decided she is a saint. Her annoyance is practical. Every pendant use gives away her position."],
  [6, "paperwork", "The paperwork won't stick", "INT. POLICE CAR", "DAY", ["kath", "ray"], "The cops arrest a demon and the paperwork will not stick. The arrested demon is not named in the source; do not silently choose one."],
  [6, "bars", "The stat bars", "INT. MAX'S ROOM", "DAY", ["max"], "Max flashback: the moral values arranged so the bars look balanced, below average to make the enemies weak. The criteria are decoupled from the values.", "Flashback"],
  [7, "postcode", "Four wrong reasons", "EXT. ARCADE POSTCODE", "DAY", [], "Four parties converge on one postcode for four wrong reasons. People dying of water failure dully. No shared explanatory scene; separate thread grammars until episode eight."],
  [7, "play", "Make it play something", "INT. ARCADE", "DAY", ["martin"], "Martin is already there with the machine plugged in, trying to make it play something. His fluorescent, flat, off-centre grammar still applies in episode seven."],
  [7, "audit", "Nobody is auditing us", "INT. LIMBO ADMINISTRATION", "CONTINUOUS", [], "Someone in administration realises nobody is auditing them either. This official is not silently assigned to Brenda or Gordon. Limbo is unaffected by time."],
  [7, "attempts", "Just clear our past attempts", "INT. MAX'S ROOM", "DAY", ["max"], "Max flashback: just clear our past attempts. He means two seasons of bad placements. Minimising the window sends the signal.", "Flashback"],
  [8, "arcade", "Everyone is wrong", "INT. ARCADE", "DAY", ["martin", "kath", "ray", "angel-one", "angel-two", "vassago", "reek", "tamsin"], "Martin defends his collection, cops arrest people in sequence, demons and angels arrive together and each assumes the other is the target. All grammars collapse to neutral ordinary coverage."],
  [8, "upstairs", "The menu / the desk / ENTER", "INT. ARCADE UPSTAIRS / LIMBO DESK", "CONTINUOUS", ["jodie", "nina"], "Jodie gets through because she is eleven and ignored. Nina cannot read the menu; Max knows where the fields are, but the bible retains flashbacks only. Limbo protects the outage. Nina wins an argument at a desk. The correction is an auction bid outbidding Martin, not a rewind. ENTER. No flash, sound or score."],
  [8, "last", "SOLD / just one question", "INT. STORAGE UNIT / LIMBO", "CONTINUOUS", [], "Shutter down, machine unopened in the dark. Lot sticker: number, date, SOLD. Then timeless Limbo, the same queue, a man at the desk with one question. No epilogue, no faces, no resolution for anyone.", "Tag"],
];

// Legacy reference boards wired into the storyboard in filename order. The build reads
// public/images/rapture/<prefix>-NN.jpg from disk, so adding a keyframe only needs a
// rebuild; a number with no file becomes a "keyframe missing" card holding its slot.
// Shot type, movement, lens and durations on these frames are working placeholders.
export const legacyBoards = [
  { prefix: "shot", scene: "rapture-ep1-mugging", board: "Cold open", lighting: "Practical night", cast: [], review: "Night alley under sodium streetlight and shopfront spill; the old woman, the handbag and the knife's journey." },
  { prefix: "a1s1", scene: "rapture-ep1-st-judes", board: "St Jude's", lighting: "Natural daylight", cast: ["nina"], review: "Daylight interiors at St Jude's; locked-off wide grammar, never follow Nina." },
  { prefix: "a1s3", scene: "rapture-ep1-washing-up", board: "Washing up", lighting: "Natural daylight", cast: ["nina"], review: "Clearing the hall and collecting water around St Jude's; Nina's daylight grammar." },
  { prefix: "a1s4", scene: "rapture-ep1-storage", board: "Storage facility", lighting: "High key", cast: ["martin"], review: "Flat institutional fluorescent look, locked off, slightly off-centre; aggrieved, never grieving." },
  { prefix: "a2s1", scene: "rapture-ep1-cops", board: "Police / car park", lighting: "Overcast soft", cast: ["kath", "ray"], review: "Static windscreen two-shot and car-park wide; handheld only for violence, no reaction cuts." },
  { prefix: "ep2s1", scene: "rapture-ep2-limbo", board: "Limbo", lighting: "High key", cast: ["brenda", "gordon"], review: "Cathedral scale against the flat close desk; four-second spoken reverberation; Limbo is outside time." },
  { prefix: "ep2s2", scene: "rapture-ep2-raid", board: "First raid", lighting: "Practical night", cast: ["danny", "jodie"], review: "Tight red-practical handheld night coverage; never a whole room." },
  { prefix: "ep2s3", scene: "rapture-ep2-intake", board: "Hell intake", lighting: "High key", cast: ["vassago", "reek", "tamsin"], review: "Fixed high-corner 4:3 surveillance, slight fisheye, faint timecode; never moves, never close." },
  { prefix: "w3", scene: "rapture-ep2-night-drive", board: "Night drive (Wave 3)", lighting: "Practical night", cast: ["danny", "jodie"], review: "Earlier night-drive coverage; teal/sodium elements and horror framing are superseded — review against the current Crane grammar. The background figure is an earlier visual idea, not a character." },
];

// Existing assets are references, not newly generated or newly approved series coverage.
export const referenceBoards = [
  { id: "nina", title: "Nina — locked off, daylight", description: "Wide, symmetrical, deep focus; she enters and leaves frames. Never follow her. Only the vision goes handheld.", items: [["/images/rapture/sheets/nina.jpg", "Existing character sheet; not a camera setup."], ["/images/rapture/a1s1-01.jpg", "Legacy St Jude's reference; review against the current grammar before production."]] },
  { id: "cops", title: "Cops — the identical two-shot", description: "Static windscreen two-shot from the bonnet and a wide across the car park. Handheld only for violence, then back. No reaction cuts.", items: [["/images/rapture/a2s1-01.jpg", "Existing police sequence reference, not newly boarded coverage."], ["/images/rapture/sheets/kath.jpg", "Kath — existing identity sheet."], ["/images/rapture/sheets/ray.jpg", "Ray — existing identity sheet."]] },
  { id: "limbo", title: "Limbo — cathedral plus admin", description: "Frontal proscenium, vast vertical scale and packed queues; hard cuts to the flat close desk. Four desks, serving 41. Four-second spoken reverberation. Time does not affect Limbo.", items: [["/images/rapture/ep2s1-01.jpg", "Legacy hall image: review cathedral scale, modern fittings and crowd against current bible."], ["/images/rapture/sheets/brenda.jpg", "Brenda — existing identity sheet."], ["/images/rapture/sheets/gordon.jpg", "Gordon — existing identity sheet."]] },
  { id: "hell", title: "Hell — fixed surveillance", description: "Grey corporate office, blank target board, deflating balloons. 4:3, fixed high corner, slight fisheye, faint timecode. Never moves, never close. Same grammar for demons on earth.", items: [["/images/rapture/ep2s3-01.jpg", "Legacy Hell image, reference only; verify 4:3 high-corner framing before use."], ["/images/rapture/sheets/vassago.jpg", "Vassago — existing identity sheet."], ["/images/rapture/sheets/reek.jpg", "Reek — existing identity sheet."], ["/images/rapture/sheets/tamsin.jpg", "Tamsin — existing identity sheet."]] },
  { id: "martin", title: "Martin — flat fluorescent", description: "Locked off, slightly off-centre, institutional beige. Four guitars, no output in eleven years. Aggrieved, never grieving.", items: [["/images/rapture/sheets/martin.jpg", "Existing Martin identity sheet; no dedicated new keyframe generated."]] },
  { id: "1980", title: "1980 — the beautiful exception", description: "Warm, grainy, anamorphic. Heavy practical sodium and tungsten through net curtains. No dedicated reference selected yet; do not borrow the Crane red look.", items: [] },
  { id: "visions", title: "Visions — recorded, not divine", description: "Wrong aspect ratio, dropped frames, blown exposure and hiss. Bad home video from the tracker's recorded view. Not white light and choral swell. No dedicated reference selected yet.", items: [] },
  { id: "arcade", title: "Episode eight — no style", description: "Neutral, ordinary, unstyled. All threads' grammars collapse here, and only here. No dedicated reference selected yet.", items: [] },
];
