// Hand-authored production metadata. Dialogue and episode summaries are read from docs/rapture.
// Run npm run build:rapture to rebuild the portable project; --check detects source drift.
export const projectId = "74a9cb34-9e80-4a04-a614-000000000014";
export const sceneId = "rapture-ep4-number-fourteen";
export const createdAt = "2026-09-20T00:00:00.000Z";
export const characterId = name => `rapture-${name}`;
export const grammar = "Handheld, tight, dark. Red practical sources only. Never a wide establishing shot; never show a whole room. Dry, deadpan British black comedy, not noir, horror performance or tragedy. No pathos, no grief, no score, no reaction inserts.";
export const redLight = "Red practical sources only: the letterbox, red dashboard indicators and the kettle's red indicator. Deep darkness outside those small pools. No white, blue, teal, sodium or daylight fill; red is a physical source, never an overall colour grade. Jodie's collar headlamp stays off.";

// First sentences carry the visual identity into the prompt studio. No invented names for unnamed roles.
const cast = [
  ["nina", "Sister Nina Doyle", "Protagonist / St Jude's", "45", "Runs St Jude's, a residential house for people the system gave up on. Self-sufficient, can re-plumb a building, lies fluently to authority; gentle with the genuinely broken, brutal with anyone coasting. Daughter of the absconding rockstar, whom she never knew. Half-angel and ineligible for sorting: nepotism, not tragedy. Faith is functional; God is her employer and she has views about management. Treats divine instruction as an unreliable supplier. Finds being called a saint ridiculous.", ["Practical", "Stubborn", "Self-sufficient"], "sage", "nina"],
  ["kath", "PC Kath Bridges", "Police / moral justice", "30s", "White British police officer in her thirties. Sincerely believes she was left behind to teach moral justice; cannot remember who said so. Maintains paperwork and cites vanished superiors. Notices the wrong details with total commitment. Mild grievance, never fear or amazement. Thinks Ray is the one who gets carried away.", ["Sincere", "Pedantic", "Aggrieved"], "sand", "kath"],
  ["ray", "PC Ray Okonjo", "Police / moral justice", "30s", "Black British police officer in his thirties. Sincerely believes he was left behind to teach moral justice; cannot remember who said so. Maintains paperwork and cites vanished superiors. Follows the wrong details nowhere. Mild grievance, never fear or amazement. Thinks Kath is the one who gets carried away.", ["Sincere", "Pedantic", "Aggrieved"], "sand", "ray"],
  ["danny", "Danny Crane", "Father / water scavenger", "40", "Forty, olive waxed jacket, canvas satchel, untidy dark hair and stubble. Scavenging for water with his daughter Jodie. Has rules: nothing off anyone still alive. Cannot let her be right because the rules are the last bit of parenting he has. Keeps a laminated rules card. Dry and occupied by logistics, never played for grief.", ["Rule-bound", "Practical", "Protective"], "sage", "danny"],
  ["jodie", "Jodie Crane", "Daughter / water scavenger", "11", "Eleven, short sandy hair, navy hoodie under an oversized olive jacket, backpack and a headlamp on her collar. The headlamp stays off in Number Fourteen. Better at crime than Danny and knows it without cruelty. Sees his rules will get them killed. Her mother was raptured and judged worthy. No pathos performance.", ["Observant", "Resourceful", "Direct"], "sand", "jodie"],
  ["martin", "Martin", "Collector / Max's father", "40s", "Failed musician in a denim jacket correct in 1994, hair long at the back on principle. Four guitars, nothing written in eleven years. Collected the rockstar's belongings at estate sales; won the terminal at auction and has it filed as period junk. Cannot reach his son. Aggrieved rather than grieving. Never learns what the machine is.", ["Possessive", "Aggrieved", "Persistent"], "clay", "martin"],
  ["max", "Max", "Flashbacks / accidental operator", "14", "Fourteen-year-old son of Martin, making a retro poster for his esports team The Raptors. Misspells it RAPTURES, balances moral-criterion bars as graphic design, sets opponents weak, asks to clear past attempts, then minimises the window. Alive, unreachable; flashbacks only. Worried he is in trouble, not wracked with guilt. The series does not laugh at him.", ["Unaware", "Competitive", "Practical"], "sand"],
  ["brenda", "Brenda", "Limbo guide", "50s", "Limbo guide in her fifties, cardigan over robes behind a folding table. Thirty years in post; customer-service warmth. Sincere and bored. Cannot tell the religions apart any more. Has no records on anyone. Talks over the cathedral's four-second reverberation.", ["Sincere", "Bored", "Courteous"], "rose", "brenda"],
  ["gordon", "Gordon", "Limbo guide", "60s", "Limbo guide in his sixties, cardigan over robes behind a folding table. Thirty years in post; customer-service warmth. Sincere and bored. Cannot tell the religions apart any more. Has no records on anyone. Talks over the cathedral's four-second reverberation.", ["Sincere", "Bored", "Courteous"], "rose", "gordon"],
  ["vassago", "Vassago", "Hell / intake manager", "50s", "Hell's intake manager in his fifties, short sleeves and a lanyard. In charge, no idea. More concerned with deflating birthday balloons than the intake collapse. Instantly accepts Tamsin's theory that Heaven stole the damned for its numbers. Investigates entirely the wrong thing.", ["Bureaucratic", "Certain", "Incompetent"], "clay", "vassago"],
  ["reek", "Reek", "Hell / intake", "30s", "Hell intake employee in his thirties. Has no opinions. Works on a grey corporate open-plan floor with a blank target board and deflating birthday balloons. Goes along with the theory that Heaven stole their queue.", ["Compliant", "Uncurious", "Bureaucratic"], "clay", "reek"],
  ["tamsin", "Tamsin", "Hell / intake investigator", "20s", "Keen Hell intake employee in her twenties carrying a folder. Proposes that Heaven stole the damned to improve its numbers. Her idea becomes the working theory immediately. Investigates the wrong thing all season. Starts enjoying being a person.", ["Keen", "Sincere", "Mistaken"], "clay", "tamsin"],
  ["pat", "Pat", "Hell / undercover auditor", "70s disguise", "A demon disguised as an old lady in her seventies. Too much rouge, too many doilies, a tin containing only boiled sweets and a husband whose name changes. Uses water as bait for an audit. Keeps an arrangement going after violence but is frosty as after a parking dispute. Distinct from the woman at Number Fourteen; never substitute that woman's sheet for Pat.", ["Nosy", "Overcommitted", "Businesslike"], "rose"],
  ["field-officer", "Hell's third field officer", "Hell / basement interrogation", "", "A female demon with a blank chained in a cellar. Interrogating him about the missing damned, gets only the apology. Reads it as resistance by the system rather than a man doing what he is told. Has notes and thinks she is close. Surveillance grammar, never moving or close.", ["Certain", "Thorough", "Mistaken"], "clay"],
  ["angel-one", "First recovery angel", "Heaven / equipment recovery", "", "One of two angels sent down to recover the absconder's equipment. Smug rather than stupid and equally useless. Has permissions, not power. No name, age or independent backstory supplied.", ["Smug", "Authorised", "Useless"], "sand"],
  ["angel-two", "Second recovery angel", "Heaven / equipment recovery", "", "One of two angels sent down to recover the absconder's equipment. Smug rather than stupid and equally useless. Has permissions, not power. No name, age or independent backstory supplied.", ["Smug", "Authorised", "Useless"], "sand"],
  ["alan", "Alan", "Blank / Nina's passenger", "50s", "A blank in his fifties, fleece and sensible shoes, carrying a bag for life containing another bag. Nina picks him up at a wrong lockup. The apology is not a reliable test. Not automatically the chained man from the basement; no identity link has been supplied.", ["Boring", "Compliant", "Ordinary"], "sage"],
  ["absconder", "The absconder", "1980 / angel turned rockstar", "", "An angel who steals a terminal to live inside creation in 1980. Edits appearance, charisma, confidence and musical ability to the ceiling, leaves social status at default. Conjures a guitar; writes by entering tempo and key. Gives the detached tracker to a woman he loves. Nina's father. Dies five years later and declines undo with NO. Appearance and age are not locked.", ["Wilful", "Charismatic", "Decisive"], "clay"],
  ["woman-fourteen", "The Woman — Number Fourteen", "Number Fourteen / house rules", "50s", "Woman in her fifties with grey-brown hair in an untidy bun, rumpled tan housecoat over a floral blouse, and a Tesco bag stuffed with crumpled papers. Mid-sentence when the door opens. Plays her situation as house rules and a complaint to the council. The table set for six is never played. No visible listener. This supporting character is not Pat and is not identified as a blank or demon.", ["Matter-of-fact", "Occupied", "Insistent"], "rose", "crazed-woman"],
  ["rescued-blank", "The rescued blank", "Basement / surveillance window", "", "A man chained in a cellar by Hell's third field officer. Gives the apology, doing what he is told. Rescued by Danny and Jodie; talks about laminate flooring. Hell watches through him, putting the rescuers on its map. Do not assume this is Alan. No name or age supplied.", ["Compliant", "Tedious", "Ordinary"], "sand"],
];

export const characters = cast.map(([key, name, role, age, description, traits, color, sheet]) => ({
  id: characterId(key), name, role, age, description, traits, color, createdAt,
  ...(sheet ? { image: `/images/rapture/sheets/${sheet}.jpg` } : {}),
  relations: [],
}));
const reverse = { Parent: "Child", Child: "Parent", Colleague: "Colleague" };
function link(a, b, kind, note) {
  characters.find(c => c.id === characterId(a)).relations.push({ id: `rapture-link-${a}-${b}`, targetId: characterId(b), kind, note });
  characters.find(c => c.id === characterId(b)).relations.push({ id: `rapture-link-${b}-${a}`, targetId: characterId(a), kind: reverse[kind], note });
}
link("danny", "jodie", "Child", "Father and daughter scavenging for water; rules versus practical experience.");
link("martin", "max", "Child", "Martin cannot reach his son; Max borrowed the terminal for a poster.");
link("nina", "absconder", "Parent", "Nina never knew her father; the pendant was the terminal's tracker.");
link("kath", "ray", "Colleague", "Each thinks the other gets carried away.");
link("brenda", "gordon", "Colleague", "Thirty years behind the desk, no records on anyone.");
link("vassago", "reek", "Colleague", "Hell's intake floor.");
link("vassago", "tamsin", "Colleague", "He adopts her stolen-queue theory immediately.");
link("reek", "tamsin", "Colleague", "Investigating the wrong thing together.");
link("angel-one", "angel-two", "Colleague", "Recover the missing equipment.");

// Titles, working running times and on-camera cast for the thirteen numbered source shots.
// Durations are editorial estimates, NEVER the duration of just the written pause.
export const shotPlan = [
  { title: "The headlight switch", duration: 5, characters: [], image: "01-switch.jpg", note: "CU replaces the superseded WS. Headlight state is conveyed by the switch; no white beam is shown. Danny's hand only." },
  { title: "Rule two", duration: 15, characters: ["danny", "jodie"], image: "02-card.jpg", note: "Inside the cab, not the cops' bonnet-mounted two-shot. Small red dashboard practical only." },
  { title: "It's very cold", duration: 15, characters: ["danny"], image: "03-knocks.jpg", note: "Three knocks, then the full 3-second and 2-second pauses. Jodie stays off camera." },
  { title: "Mid-sentence", duration: 10, characters: ["woman-fourteen"], image: "04-mid-sentence.jpg", note: "Door swing and reopening occur within this setup. No listener, shadow-person or reaction insert." },
  { title: "Six places", duration: 10, characters: ["woman-fourteen", "danny"], image: "05-six-places.jpg", note: "Over the woman's shoulder without changing the source's MS designation. Table remains an unremarked cropped background detail; never show a whole room." },
  { title: "Tuesday was Thursday", duration: 23, characters: ["woman-fourteen", "danny"], image: "06-six-cups.jpg", note: "Six cups. Kettle indicator and letterbox spill only. Upstairs is intermittently dead locally, not yet the episode-five system-wide milestone." },
  { title: "Brown, then clear", duration: 11, characters: [], image: "07-brown-water.jpg", note: "Only the tap is on camera. Hold brown water for four full seconds before it clears. All three lines are off camera." },
  { title: "Rule one is biscuit", duration: 11, characters: ["jodie", "woman-fourteen"], image: "08-biscuit-rule.jpg", note: "Danny's line is off camera. No reaction cut." },
  { title: "No pocket", duration: 25, characters: ["danny"], image: "09-no-pocket.jpg", note: "Dedicated CU: Danny, the card and the pocketless jacket, with Jodie's hand entering frame holding the biscuit. Keep the slow blink and both 2-second pauses in one setup. Check card legibility and jacket-pocket continuity before approving." },
  { title: "The pipes", duration: 22, characters: ["jodie", "woman-fourteen"], image: "10-the-pipes.jpg", note: "Dedicated biscuit/bottle handover keyframe at the sink. Bottle returned full, cold, no air gap; no magical flash. Danny is off camera. Check the bottle fill line before approving." },
  { title: "About the council", duration: 13, characters: ["danny", "jodie"], image: "11-council.jpg", note: "Inside the moving cab. Vehicle exterior lights off. No reflective ending or grief." },
  { title: "The light stays on", duration: 5, characters: [], image: "12-passing-door.jpg", note: "MS replaces the superseded WS. Only a passing van panel and a slice of door, never a street establishing shot. No exterior van lights." },
  { title: "The unfinished complaint", duration: 10, characters: ["woman-fourteen"], image: "13-complaint.jpg", note: "Final mid-complaint pose at the door, from the street. No listener is revealed. The door closes after the 2-second pause, then a hard CUT TO BLACK, not a fade. Check door colour against shot 4 and keep red the only practical before approving." },
];

// Planning outlines, not invented finished scripts. Locations/times are provisional except for explicit bible grammar.
export const outlinePlan = [
  [1, "mugging", "The mugging", "EXT. ALLEY", "NIGHT", [], "The mugging. The knife starts its journey through the old woman's handbag and the support group.", "Cold open"],
  [1, "st-judes", "St Jude's and the rapture", "INT. ST JUDE'S", "DAY", ["nina"], "Nina at St Jude's; the rapture. One ignored complaint about water pressure. Locked off, wide, deep focus, daylight, symmetrical."],
  [1, "cops", "Birds, arrest ourselves, the taser", "INT. POLICE CAR", "DAY", ["kath", "ray"], "Birds; arrest ourselves; the taser. Static windscreen two-shot from the bonnet and a wide across the car park. Handheld only during violence, then identical static framing. No reaction cuts."],
  [1, "bearing", "The pendant and first vision", "INT./EXT. ST JUDE'S / ROAD", "DAY", ["nina"], "Nina's aftermath, the pendant, the first vision; she drives. The vision is the tracker's recorded view, not divine revelation. Only this interruption breaks Nina's grammar."],
  [1, "storage", "Martin at the storage unit", "INT. STORAGE UNIT", "DAY", ["martin"], "Martin at the storage unit. No mechanism revealed. Flat fluorescent light, locked off, slightly off-centre."],
  [1, "no", "1980 thread — NO", "INT. HOTEL ROOM", "NIGHT", ["absconder"], "Tag for the 1980 thread, ending on NO. Preserve the bible's five-years-later death chronology; do not silently date the hotel scene 1980. Warm, grainy anamorphic practical light.", "Tag"],
  [2, "limbo", "The family at the desk", "INT. LIMBO CATHEDRAL", "CONTINUOUS", ["brenda", "gordon"], "The family, branches of Christianity, seventy-two virgins, husband led away. Frontal proscenium, vast vertical space, hard cut to the flat close desk. Four-second reverberation."],
  [2, "raid", "The first raid", "INT. HOUSE", "NIGHT", ["danny", "jodie"], "Danny and Jodie's first raid for water. Handheld, tight and dark, red practical sources only. Never a whole room."],
  [2, "intake", "The intake floor", "INT. HELL INTAKE", "CONTINUOUS", ["vassago", "reek", "tamsin"], "Hell's intake collapse goes unnoticed behind balloon concerns. Fixed high-corner surveillance, 4:3, slight fisheye, faint timecode. Never close."],
  [2, "alan", "The first wrong lockup", "EXT. LOCKUP", "DAY", ["nina", "alan"], "Nina's first wrong lockup; she acquires Alan. Nina's locked-off daylight grammar."],
  [3, "arrivals", "Both sides come down", "EXT. EARTH — LOCATION TBC", "DAY", ["angel-one", "angel-two", "pat", "field-officer"], "Demons and angels arrive, badly. Keep faction coverage separate; no invented shared scene. Demons retain fixed surveillance grammar on earth."],
  [3, "test", "A worthless screening method", "INT. POLICE CAR", "DAY", ["kath", "ray"], "Blanks established. The cops invent a test around I can only apologise and never doubt it. Half of real humanity says it too."],
  [3, "group", "Recruited / brown water", "INT. UNDERGROUND MEETING PLACE", "NIGHT", ["danny", "jodie"], "Danny and Jodie recruited by the underground group. Brown water. Tight red practical handheld coverage; no full-room tableau."],
  [3, "home", "A collection and no son", "INT. MARTIN'S HOME", "DAY", ["martin"], "Martin comes home to a collection and no son. Aggrieved, not grieving. Flat, fluorescent, off-centre."],
  [4, "pat", "Pat's house — the old lady", "INT./EXT. PAT'S HOUSE / GATE", "NIGHT", ["pat", "danny", "jodie"], "Jodie on the settee, Danny in the kitchen, knife and fork, fork through the forearm, bottles by the gate. This is NOT Number Fourteen. Demon viewpoints retain fixed high-corner 4:3 surveillance; Crane viewpoints stay tight red handheld. Do not blend the grammars within a shot."],
  [4, "meetings", "Survivors' meetings", "INT. MEETING PLACE", "DAY", [], "Grandma and the dog are reported as proof they are here to maintain order. Someone mentions a nun. No mechanism explanation or catch-up scene."],
  [5, "basement", "The interrogation", "INT. CELLAR", "NIGHT", ["field-officer", "rescued-blank"], "The chained blank. The interrogation goes nowhere. The officer has notes and thinks she is close. Fixed high-corner surveillance, never close; the violence is not spectacular."],
  [5, "rescue", "Laminate flooring", "INT. CELLAR / EXIT", "NIGHT", ["danny", "jodie", "rescued-blank"], "Danny and Jodie rescue the man who talks about laminate flooring. Hell is watching through him. Upstairs taps are dead. The Crane coverage remains tight red handheld."],
  [5, "scent", "The cops pick up Danny's scent", "INT. POLICE CAR", "DAY", ["kath", "ray"], "Property-law enforcement over water scavenging. Static windscreen two-shot; wrong details pursued sincerely."],
  [5, "misspelling", "RAPTURES", "INT. MAX'S ROOM", "DAY", ["max"], "Max flashback: the misspelling of The Raptors. He is alive and unreachable, not a present-day participant.", "Flashback"],
  [6, "dry", "The taps fail", "INT. MEETING PLACE", "NIGHT", ["danny", "jodie"], "Dry taps. The group turns on itself; a moment of clarity. The apocalypse as a maintenance backlog, never a tragic performance."],
  [6, "saint", "A bearing that isn't wrong", "EXT. ROAD", "DAY", ["nina", "alan"], "Nina gets a correct bearing and is found by people who have decided she is a saint. Her annoyance is practical. Every pendant use gives away her position."],
  [6, "paperwork", "The paperwork won't stick", "INT. POLICE CAR", "DAY", ["kath", "ray"], "The cops arrest a demon and the paperwork will not stick. The arrested demon is not named in the source; do not silently choose one."],
  [6, "bars", "The stat bars", "INT. MAX'S ROOM", "DAY", ["max"], "Max flashback: the moral values arranged so the bars look balanced, below average to make the enemies weak. The criteria are decoupled from the values.", "Flashback"],
  [7, "postcode", "Four wrong reasons", "EXT. ARCADE POSTCODE", "DAY", [], "Four parties converge on one postcode for four wrong reasons. People dying of water failure dully. No shared explanatory scene; separate thread grammars until episode eight."],
  [7, "play", "Make it play something", "INT. ARCADE", "DAY", ["martin"], "Martin is already there with the machine plugged in, trying to make it play something. His fluorescent, flat, off-centre grammar still applies in episode seven."],
  [7, "audit", "Nobody is auditing us", "INT. LIMBO ADMINISTRATION", "CONTINUOUS", [], "Someone in administration realises nobody is auditing them either. This official is not silently assigned to Brenda or Gordon. Limbo is unaffected by time."],
  [7, "attempts", "Just clear our past attempts", "INT. MAX'S ROOM", "DAY", ["max"], "Max flashback: just clear our past attempts. He means two seasons of bad placements. Minimising the window sends the signal.", "Flashback"],
  [8, "arcade", "Everyone is wrong", "INT. ARCADE", "DAY", ["martin", "kath", "ray", "angel-one", "angel-two", "vassago", "reek", "tamsin"], "Martin defends his collection, cops arrest people in sequence, demons and angels arrive together and each assumes the other is the target. All grammars collapse to neutral ordinary coverage."],
  [8, "upstairs", "The menu / the desk / ENTER", "INT. ARCADE UPSTAIRS / LIMBO DESK", "CONTINUOUS", ["jodie", "nina"], "Jodie gets through because she is eleven and ignored. Nina cannot read the menu; Max knows where the fields are, but the bible retains flashbacks only. Limbo protects the outage. Nina wins an argument at a desk. The correction is an auction bid outbidding Martin, not a rewind. ENTER. No flash, sound or score."],
  [8, "last", "SOLD / just one question", "INT. STORAGE UNIT / LIMBO", "CONTINUOUS", [], "Shutter down, machine unopened in the dark. Lot sticker: number, date, SOLD. Then timeless Limbo, the same queue, a man at the desk with one question. No epilogue, no faces, no resolution for anyone.", "Tag"],
];

// Existing assets are references, not newly generated or newly approved series coverage.
export const referenceBoards = [
  { id: "nina", title: "Nina — locked off, daylight", description: "Wide, symmetrical, deep focus; she enters and leaves frames. Never follow her. Only the vision goes handheld.", items: [["/images/rapture/sheets/nina.jpg", "Existing character sheet; not a camera setup."], ["/images/rapture/a1s1-01.jpg", "Legacy St Jude's reference; review against the current grammar before production."]] },
  { id: "cops", title: "Cops — the identical two-shot", description: "Static windscreen two-shot from the bonnet and a wide across the car park. Handheld only for violence, then back. No reaction cuts.", items: [["/images/rapture/a2s1-01.jpg", "Existing police sequence reference, not newly boarded coverage."], ["/images/rapture/sheets/kath.jpg", "Kath — existing identity sheet."], ["/images/rapture/sheets/ray.jpg", "Ray — existing identity sheet."]] },
  { id: "limbo", title: "Limbo — cathedral plus admin", description: "Frontal proscenium, vast vertical scale and packed queues; hard cuts to the flat close desk. Four desks, serving 41. Four-second spoken reverberation. Time does not affect Limbo.", items: [["/images/rapture/ep2s1-01.jpg", "Legacy hall image: review cathedral scale, modern fittings and crowd against current bible."], ["/images/rapture/sheets/brenda.jpg", "Brenda — existing identity sheet."], ["/images/rapture/sheets/gordon.jpg", "Gordon — existing identity sheet."]] },
  { id: "hell", title: "Hell — fixed surveillance", description: "Grey corporate office, blank target board, deflating balloons. 4:3, fixed high corner, slight fisheye, faint timecode. Never moves, never close. Same grammar for demons on earth.", items: [["/images/rapture/ep2s3-01.jpg", "Legacy Hell image, reference only; verify 4:3 high-corner framing before use."], ["/images/rapture/sheets/vassago.jpg", "Vassago — existing identity sheet."], ["/images/rapture/sheets/reek.jpg", "Reek — existing identity sheet."], ["/images/rapture/sheets/tamsin.jpg", "Tamsin — existing identity sheet."]] },
  { id: "martin", title: "Martin — flat fluorescent", description: "Locked off, slightly off-centre, institutional beige. Four guitars, no output in eleven years. Aggrieved, never grieving.", items: [["/images/rapture/sheets/martin.jpg", "Existing Martin identity sheet; no dedicated new keyframe generated."]] },
  { id: "1980", title: "1980 — the beautiful exception", description: "Warm, grainy, anamorphic. Heavy practical sodium and tungsten through net curtains. No dedicated reference selected yet; do not borrow the Crane red look.", items: [] },
  { id: "visions", title: "Visions — recorded, not divine", description: "Wrong aspect ratio, dropped frames, blown exposure and hiss. Bad home video from the tracker's recorded view. Not white light and choral swell. No dedicated reference selected yet.", items: [] },
  { id: "arcade", title: "Episode eight — no style", description: "Neutral, ordinary, unstyled. All threads' grammars collapse here, and only here. No dedicated reference selected yet.", items: [] },
];
