"use client";

import { useCallback, useRef } from "react";
import { ArrowRight, ArrowUpRight, Camera, FileInput, Images, ListOrdered, CheckCheck, ChevronRight, Clapperboard, Clock3, FileText, Film, LayoutGrid, Lightbulb, MessageSquare, NotebookPen, Pencil, Plus, Sparkles, UserRound, Video } from "lucide-react";
import type { FilmProject, ProjectNote, Scene } from "@/lib/types";
import { groupScenes, kindMeta, renderRows } from "@/lib/structure";
import { EmptyState, FrameLogo } from "./ui";
import { onImageError, resolveImage } from "@/lib/image";
import { sceneNumber } from "@/lib/frame-order";
import { formatShortDate } from "@/lib/format";

export function NotesView({ project, onAdd, onEdit }: { project: FilmProject; onAdd: () => void; onEdit: (note: ProjectNote) => void }) {
  return <section className="view-enter"><div className="section-heading"><div><div className="section-title-row"><h2>Notes & ideas</h2><span className="count-badge">{project.notes.length}</span></div><p>The thoughts between the takes.</p></div><button className="button button-primary" onClick={onAdd}><Plus size={16} />Add a note</button></div>{project.notes.length ? <div className="notes-grid">{project.notes.map(note => <button key={note.id} className={`note-card ${note.color}`} onClick={() => onEdit(note)}><div className="note-card-top"><NotebookPen size={18} /><Pencil size={14} /></div><h3>{note.title}</h3><p>{note.content}</p><div className="note-card-bottom"><span>Jamie’s notebook</span><span>{formatShortDate(note.createdAt)}</span></div></button>)}<button className="new-note-card" onClick={onAdd}><Plus size={24} strokeWidth={1.4} /><span>Catch the next idea.</span><small>Big, small, or not quite ready yet.</small></button></div> : <EmptyState title="Good ideas need a place to land." description="Keep visual references, production reminders, and sudden sparks of inspiration together." action={onAdd} actionLabel="Write your first note" />}</section>;
}

export function OverviewView({ project, onAddScene, onEditScene, onTab, onManageActs }: { project: FilmProject; onAddScene: () => void; onEditScene: (scene: Scene) => void; onTab: (tab: string) => void; onManageActs?: () => void }) {
  const ready = project.frames.filter(frame => frame.status === "Ready").length;
  const groups = groupScenes(project);
  const boards = project.moodboards || [];
  return <section className="overview-section view-enter"><div className="overview-hero"><img src={resolveImage(project.coverImage)} alt="Film visual direction" onError={onImageError} /><div className="overview-hero-shade" /><div className="overview-hero-content"><span className="eyebrow">THE HEART OF THE STORY</span><h2>{project.description}</h2><span>{project.format} <i>·</i> {project.genre}</span></div><span className="overview-hero-brand"><FrameLogo small /></span></div>
    <div className="overview-stats">
      <button onClick={() => onTab("Screenplay")}><FileText size={19} /><div><strong>{project.scenes.length}</strong><span>Scenes in the story</span></div><ArrowUpRight size={17} /></button>
      <button onClick={() => onTab("Storyboard")}><LayoutGrid size={19} /><div><strong>{project.frames.length}</strong><span>Moments visualized</span></div><ArrowUpRight size={17} /></button>
      <button onClick={() => onTab("Shot list")}><CheckCheck size={19} /><div><strong>{ready}<small> / {project.frames.length}</small></strong><span>Shots ready for action</span></div><ArrowUpRight size={17} /></button>
      <button onClick={() => onTab("Characters")}><UserRound size={19} /><div><strong>{project.characters.length}</strong><span>People in the cast</span></div><ArrowUpRight size={17} /></button>
      <button onClick={() => onTab("Mood boards")}><Images size={19} /><div><strong>{boards.length}</strong><span>Mood boards</span></div><ArrowUpRight size={17} /></button>
      <button onClick={() => onTab("Notes")}><Lightbulb size={19} /><div><strong>{project.notes.length}</strong><span>Ideas worth keeping</span></div><ArrowUpRight size={17} /></button>
    </div>
    <div className="section-heading scenes-heading"><div><h2>The story, act by act</h2><p>A little perspective on the bigger picture.</p></div><div className="section-actions">{onManageActs && <button className="button" onClick={onManageActs}><ListOrdered size={15} />{project.acts.length ? "Acts & sequences" : "Add acts"}</button>}<button className="button" onClick={onAddScene}><Plus size={15} />Add scene</button></div></div>
    {project.scenes.length ? groups.map(group => { const total = group.scenes.length + group.parts.reduce((n, p) => n + p.scenes.length, 0); return <div key={group.key} className={`act-block level-${group.level}`}>{group.title && <div className="act-block-head"><div><span className="act-block-kicker">{group.level === "cold" ? "Before the titles" : group.subtitle || (group.level === "act" ? "Act" : "")}</span><h3>{group.title}</h3></div>{group.description && <p>{group.description}</p>}<span>{total} scene{total === 1 ? "" : "s"}</span></div>}<div className="scene-overview-list">{renderRows(group).map(row => row.kind === "header" ? <div key={row.key} className="part-divider"><span>{row.part.title}</span>{row.part.description && <small>{row.part.description}</small>}<em>{row.part.scenes.length}</em></div> : <button key={row.key} className="scene-overview-row" onClick={() => onEditScene(row.scene)}><span className="scene-overview-num">{sceneNumber(row.scene, row.index).padStart(2, "0")}</span><div><h3>{row.scene.title}{row.scene.kind && row.scene.kind !== "Standard" && <em className={`kind-badge kind-${kindMeta[row.scene.kind].tone}`}>{row.scene.kind}</em>}</h3><p>{row.scene.description}</p></div><span className="scene-location">{row.scene.location}<small>{row.scene.time}</small></span><span className="scene-frame-count"><LayoutGrid size={13} />{project.frames.filter(f => f.sceneId === row.scene.id).length} frames</span><ChevronRight size={16} /></button>)}</div></div>; }) : <EmptyState title="Where does your story begin?" description="Start with an opening scene — or a cold open that hooks us before the titles." action={onAddScene} actionLabel="Set the first scene" />}
  </section>;
}

export function ProjectsView({ projects, recent, onOpen, onNew, onImport }: { projects: FilmProject[]; recent?: boolean; onOpen: (id: string) => void; onNew: () => void; onImport?: (file?: File) => Promise<void> }) {
  const importRef = useRef<HTMLInputElement>(null);
  const sorted = recent ? [...projects].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()) : projects;
  return <section className="projects-view view-enter"><div className="workspace-heading"><div><span className="eyebrow">YOUR CREATIVE SPACE</span><h1>{recent ? "Pick up where you left off." : "Stories waiting to be told."}</h1><p>{recent ? "A little momentum goes a long way. Let’s get back to it." : "From a first spark to the final frame. It all starts here."}</p></div><div className="workspace-heading-actions"><button className="button" onClick={() => importRef.current?.click()}><FileInput size={15} />Import project</button><button className="button button-primary" onClick={onNew}><Plus size={17} />New project</button></div><input ref={importRef} type="file" accept="application/json,.json" className="sr-only" aria-label="Import project file" onChange={e => { onImport?.(e.target.files?.[0]); if (e.target) e.target.value = ""; }} /></div><div className="projects-section-title"><h2>{recent ? "Recently opened" : "All projects"}<span className="count-badge">{projects.length}</span></h2><span>{projects.reduce((sum, p) => sum + p.frames.length, 0)} frames of possibility</span></div><div className="projects-grid">{sorted.map(project => <button key={project.id} className="project-card" onClick={() => onOpen(project.id)}><div className="project-card-image"><img src={resolveImage(project.coverImage)} alt={project.title} onError={onImageError} /><span>{project.format}</span><span className="project-open-arrow"><ArrowUpRight size={20} /></span></div><div className="project-card-content"><div><span className="project-status"><i />{project.status}</span><span className="project-genre">{project.genre}</span></div><h2>{project.title}</h2><p>{project.description}</p><footer><span><Clapperboard size={13} />{project.scenes.length} scenes</span><span><LayoutGrid size={13} />{project.frames.length} frames</span><ArrowRight size={16} /></footer></div></button>)}<button className="new-project-card" onClick={onNew}><span><Plus size={27} strokeWidth={1.3} /></span><h3>Your next great story.</h3><p>Start with an idea.<br />We’ll give it a little room to grow.</p><strong>Create a project<ArrowUpRight size={14} /></strong></button></div><div className="workspace-quote"><span>“</span><p>We don’t make movies to make money,<br />we make money to make more movies.</p><small>WALT DISNEY · A LITTLE CREATIVE PERSPECTIVE</small></div></section>;
}

export function TemplatesView({ onUse }: { onUse: (template: string) => void }) {
  const templates = [
    { order: 0, id: "rapture", label: "8 × 45MIN · BRITISH BLACK COMEDY", title: "Let the Raptures Commence", description: "The current series bible, eight episode outlines, twenty cast members and Number Fourteen: thirteen shots, each with its own new AI-generated study. Existing edits stay safe.", icon: Clapperboard, image: "/images/rapture/ep4/04-mid-sentence.jpg", tags: ["Series bible", "13-shot scene", "Editable workspace"] },
    { order: 1, id: "neonoire", label: "FEATURE · NEO-NOIR · FINAL SCREENPLAY", title: "Nobody's Witness", description: "The revised feature screenplay: 103 active scenes and 342 shots, listed in screenplay scene order with stable production numbers. Every one is pictured and every image is 16:9 (1920×1080), including the 4 October long-hold passes' twenty new frames (344–363) in scenes 20, 22, 23, 29, 17 and 14; the 14 older retakes the rewrite flagged are delivered too.", icon: Film, image: "/images/neonoire/s1/03-mara-walks.jpg", tags: ["Screenplay in full", "103 scenes", "342 shots · 342 images · 16:9"] },
    { order: 2, id: "short-film", label: "THE SHORT FILM", title: "Small canvas. Big feeling.", description: "A focused three-act structure with opening, turning point, and resolution scenes. Perfect for your next short.", icon: Clapperboard, image: "/images/templates/short-film.jpg", tags: ["3-act structure", "Scene outline", "Fountain script"] },
    { order: 3, id: "feature-film", label: "THE FEATURE", title: "A world worth getting lost in.", description: "Start your feature-length screenplay with industry-familiar scene headings and an open canvas for your story.", icon: Film, image: "/images/templates/feature-film.jpg", tags: ["Screenplay starter", "Flexible structure", "Blank storyboard"] },
    { order: 4, id: "documentary", label: "THE DOCUMENTARY", title: "Real stories. New perspectives.", description: "Give your documentary a home. Build a narrative around interviews, visual sequences, and the truth you find.", icon: Video, image: "/images/templates/documentary.jpg", tags: ["Documentary format", "Visual planning", "Production notes"] },
  ].sort((a, b) => a.order - b.order);
  return <section className="templates-view view-enter"><div className="workspace-heading"><div><span className="eyebrow">A LITTLE HEAD START</span><h1>Less setup. More storytelling.</h1><p>A few thoughtful starting points for whatever you’re imagining.</p></div><span className="template-spark"><Sparkles size={30} strokeWidth={1.2} /></span></div><div className="template-grid">{templates.map(template => <article className="template-card" key={template.id}><div className="template-image"><img src={resolveImage(template.image)} alt={template.label} loading="lazy" onError={onImageError} /><span><template.icon size={27} strokeWidth={1.4} /></span></div><div className="template-content"><span className="eyebrow">{template.label}</span><h2>{template.title}</h2><p>{template.description}</p><div className="template-tags">{template.tags.map(tag => <span key={tag}>{tag}</span>)}</div><button className="button button-primary" onClick={() => onUse(template.id)}>{template.id === "rapture" ? "Open series workspace" : template.id === "neonoire" ? "Open the final screenplay" : "Make it yours"}<ArrowUpRight size={15} /></button></div></article>)}</div><div className="template-footer"><Lightbulb size={21} strokeWidth={1.4} /><div><h3>Structure is a starting point. Not a set of rules.</h3><p>Every template is completely editable. Add, remove, and make it your own.</p></div></div></section>;
}
