// Scene 3 (exterior) and Scene 4 (interior) continuity for Vera's apartment building.
// Scene 3 retaken 29 September 2026: Vera lives in an ordinary old four-storey apartment building
// somewhere else in Tokyo, beside the elevated railway — NOT the Hive. The story depends on her
// not knowing the Hive until scene 55.
export const apartmentBuildingLook = "16:9 full-bleed (1920×1080), no letterbox. EXT. VERA'S APARTMENT BUILDING (scene 3, master s3/29-apartment-block.jpg; corridor master s78/88-the-walkway.jpg; medium window s3/31-the-lit-window.jpg): Vera lives in an ordinary old four-storey grey precast-concrete apartment building somewhere else in Tokyo, beside the elevated railway — NOT the Hive (the story depends on her not knowing the Hive until scene 55; never attach keys/06-the-block.jpg to scene 3). Plain 1970s four-storey grey concrete residential block, flat roof, open external steel staircase on the left, four storeys of flat concrete panels with ONLY ONE window on the THIRD FLOOR lit with warm amber table-lamp light (floors 1, 2 and 4 dark; matching s3/31-the-lit-window.jpg and the table lamp of keys/04-veras-apartment.jpg), vertical drainpipe, standard balconies with dark metal railings and slanted rain awnings on the right (laundry left out in the rain in s3/32-laundry-in-the-rain.jpg), bicycles parked at the foot of the wall on a wet two-lane Tokyo residential street at blue-hour dusk. Squeezed between two ordinary newer five-storey beige tiled residential manshon apartment buildings — never gleaming glass office skyscrapers, never self-built cages, bolted-on shacks, tangled ducts, steam vents, vending machines on the facade or vertical neon signs. Directly behind the four-storey block runs the concrete elevated railway viaduct with steel catenary gantries; in shot 30 (s3/30-the-elevated-line.jpg, 35mm wide) a commuter train slides past on the viaduct with its warm passenger windows blurred in motion while the same third-floor window stays lit. The THREE DAYS LATER super is added in the grade, never baked into the image.";

// Scene 4 revision from the user's room and family-photo references, 25 September 2026.
// The latest direction removes the paper pendant completely, rather than relocating it.
export const apartmentLook = "16:9 full-bleed (1920×1080), no letterbox. Room follows appartment.png, with the corrected master at keys/04-veras-apartment.jpg. NO paper pendant, ceiling lantern, hanging cord or ghost reflection. Keep the single straight aluminium sliding-door mullion, rain-streaked upper glass, frosted lower panes, beige curtains and white sheers. Left: wooden louvred sideboard, brown-shaded table lamp, black stereo/cream tuner and one brass family frame. Right: wood-cased CRT with silver bezel, two right-hand dials, black stand, small radio and exactly two straight aerial rods; the weather broadcast stays on. Muted amber/olive practical light, cool grey-blue rain outside, fine 35mm grain. Low wooden table: exactly two ivory cups without saucers, Vera's left cup holds cold tea, opposite right cup is empty; one black smartphone stays face-up on the table throughout the speakerphone call. One bone-dry closed pale-blue umbrella, one curved brown wooden handle, in an off-white cylindrical stand left of the sliding door. Vera matches sheets/vera.jpg: dry shoulder-length ash-blonde hair, soft fringe, pale blue eyes, cream high-neck knit, navy trousers, black watch; charcoal wool coat only when leaving in shot 42, with brown boots. Stand empty once she takes the umbrella. Family photograph follows photo.png and corrected s4/35-the-photograph.jpg: straight brass frame, Daniel in grey suit in centre, laughing four-year-old Mara in pink on image left, serious nine-year-old Vera in cream/navy on image right, natural joined hands, Tokyo noodle shop behind. Do not substitute adult sisters or put adult Mara's wet hair/red-bird clip into the childhood photo. Keep the room and props fixed between angles; no extra handles, cups, people, limbs, captions or watermarks.";
